In [1]:
import pandas as pd
import numpy as np

In [12]:
schedules = pd.read_csv('2012_2017_schedules.csv', index_col=0)
#schedules
played_schedule = schedules.dropna()
played_schedule

,home_team_name,home_team_score,start_time,visiting_team_name,visiting_team_score
0,Cleveland Cavaliers,94.0,10/30/12 23:00,Washington Wizards,84.0
1,Los Angeles Lakers,91.0,10/30/12 23:30,Dallas Mavericks,99.0
2,Miami Heat,120.0,10/31/12 0:00,Boston Celtics,107.0
3,Chicago Bulls,93.0,10/31/12 23:00,Sacramento Kings,87.0
4,Detroit Pistons,96.0,10/31/12 23:30,Houston Rockets,105.0
5,Los Angeles Clippers,101.0,10/31/12 23:30,Memphis Grizzlies,92.0
6,New Orleans Hornets,95.0,10/31/12 23:00,San Antonio Spurs,99.0
7,Philadelphia 76ers,84.0,10/31/12 23:00,Denver Nuggets,75.0
8,Phoenix Suns,85.0,10/31/12 23:00,Golden State Warriors,87.0
9,Portland Trail Blazers,116.0,10/31/12 23:30,Los Angeles Lakers,106.0
10,Toronto Raptors,88.0,10/31/12 23:00,Indiana Pacers,90.0
11,Utah Jazz,113.0,10/31/12 23:00,Dallas Mavericks,94.0
12,San Antonio Spurs,86.0,11/2/12 0:30,Oklahoma City Thunder,84.0
13,Atlanta Hawks,102.0,11/2/12 23:30,Houston Rockets,109.0
14,Boston Celtics,88.0,11/2/12 23:30,Milwaukee Bucks,99.0
15,Charlotte Bobcats,90.0,11/2/12 23:00,Indiana Pacers,89.0
16,Cleveland Cavaliers,86.0,11/2/12 23:30,Chicago Bulls,115.0
17,Golden State Warriors,94.0,11/2/12 23:30,Memphis Grizzlies,104.0
18,Los Angeles Lakers,95.0,11/2/12 23:30,Los Angeles Clippers,105.0
19,Minnesota Timberwolves,92.0,11/2/12 23:00,Sacramento Kings,80.0
20,New Orleans Hornets,88.0,11/2/12 23:00,Utah Jazz,86.0
21,New York Knicks,104.0,11/3/12 0:00,Miami Heat,84.0
22,Oklahoma City Thunder,106.0,11/2/12 23:00,Portland Trail Blazers,92.0
23,Orlando Magic,102.0,11/2/12 23:00,Denver Nuggets,89.0
24,Phoenix Suns,92.0,11/2/12 23:00,Detroit Pistons,89.0
25,Brooklyn Nets,107.0,11/3/12 23:30,Toronto Raptors,100.0
26,Chicago Bulls,82.0,11/3/12 23:00,New Orleans Hornets,89.0
27,Dallas Mavericks,126.0,11/3/12 23:30,Charlotte Bobcats,99.0
28,Houston Rockets,85.0,11/3/12 23:00,Portland Trail Blazers,95.0
29,Indiana Pacers,106.0,11/3/12 23:00,Sacramento Kings,98.0
...,...,...,...,...,...
835,Indiana Pacers,121.0,2/11/18 22:00,New York Knicks,113.0
836,Minnesota Timberwolves,111.0,2/12/18 0:00,Sacramento Kings,106.0
837,Oklahoma City Thunder,110.0,2/12/18 0:00,Memphis Grizzlies,92.0
838,Portland Trail Blazers,96.0,2/12/18 2:00,Utah Jazz,115.0
839,Brooklyn Nets,101.0,2/13/18 0:30,Los Angeles Clippers,114.0
840,Chicago Bulls,105.0,2/13/18 1:00,Orlando Magic,101.0
841,Detroit Pistons,103.0,2/13/18 0:00,New Orleans Pelicans,118.0
842,Golden State Warriors,129.0,2/13/18 3:30,Phoenix Suns,83.0
843,Philadelphia 76ers,108.0,2/13/18 0:00,New York Knicks,92.0
844,Utah Jazz,101.0,2/13/18 2:00,San Antonio Spurs,99.0
845,Dallas Mavericks,109.0,2/14/18 1:30,Sacramento Kings,114.0
846,Denver Nuggets,117.0,2/14/18 3:30,San Antonio Spurs,109.0
847,Milwaukee Bucks,97.0,2/14/18 1:00,Atlanta Hawks,92.0
848,Minnesota Timberwolves,108.0,2/14/18 1:00,Houston Rockets,126.0
849,Oklahoma City Thunder,112.0,2/14/18 1:00,Cleveland Cavaliers,120.0
850,Toronto Raptors,115.0,2/14/18 0:00,Miami Heat,112.0
851,Boston Celtics,119.0,2/15/18 1:00,Los Angeles Clippers,129.0
852,Brooklyn Nets,103.0,2/15/18 0:30,Indiana Pacers,108.0
853,Chicago Bulls,98.0,2/15/18 1:00,Toronto Raptors,122.0
854,Detroit Pistons,104.0,2/15/18 0:00,Atlanta Hawks,98.0
855,Houston Rockets,100.0,2/15/18 1:00,Sacramento Kings,91.0
856,Memphis Grizzlies,114.0,2/15/18 1:00,Oklahoma City Thunder,121.0
857,New Orleans Pelicans,139.0,2/15/18 1:00,Los Angeles Lakers,117.0
858,New York Knicks,113.0,2/15/18 0:30,Washington Wizards,118.0
859,Orlando Magic,102.0,2/15/18 0:00,Charlotte Hornets,104.0
860,Philadelphia 76ers,104.0,2/15/18 0:00,Miami Heat,102.0
861,Portland Trail Blazers,123.0,2/15/18 3:30,Golden State Warriors,117.0
862,Utah Jazz,107.0,2/15/18 2:00,Phoenix Suns,97.0
863,Milwaukee Bucks,123.0,2/16/18 1:00,Denver Nuggets,134.0
864,Minnesota Timberwolves,119.0,2/16/18 2:00,Los Angeles Lakers,111.0

In [6]:
box_scores = pd.read_csv('2012_2017_box_scores.csv', index_col=0)
box_scores

,Unnamed: 0.1,assists,blocks,date,defensive_rebounds,field_goal_attempts,field_goals,first_name,free_throw_attempts,free_throws,...,opponent,personal_fouls,points,seconds_played,steals,team,three_point_field_goal_attempts,three_point_field_goals,total_rebounds,turnovers
0,0,3,0,2012-10-30,9,16,10,LeBron,5,4,...,BOS,2,26,1732.0,2,MIA,4,2,10,0
1,1,9,2,2012-10-30,11,7,3,Anderson,3,3,...,WAS,4,9,2242.0,0,CLE,0,0,23,1
2,2,6,3,2012-10-30,9,19,8,Pau,8,6,...,DAL,2,23,2419.0,0,LAL,1,1,13,2
3,3,5,0,2012-10-30,5,15,6,Paul,9,9,...,MIA,3,23,2434.0,2,BOS,4,2,5,0
4,4,4,1,2012-10-30,1,22,10,Dwyane,11,9,...,BOS,3,29,2107.0,2,MIA,0,0,3,4
5,5,13,0,2012-10-30,7,14,9,Rajon,4,2,...,MIA,4,20,2613.0,0,BOS,2,0,7,4
6,6,3,1,2012-10-30,6,20,11,Kyrie,5,4,...,WAS,4,29,2074.0,0,CLE,6,3,6,4
7,7,2,0,2012-10-30,2,7,5,Ray,8,7,...,BOS,1,19,1835.0,0,MIA,3,2,2,0
8,8,1,3,2012-10-30,8,15,8,Chris,4,3,...,BOS,3,19,2217.0,0,MIA,1,0,10,1
9,9,4,0,2012-10-30,2,12,8,Darren,2,1,...,LAL,2,17,1920.0,3,DAL,1,0,2,2
10,10,0,0,2012-10-30,1,14,11,Kobe,0,0,...,DAL,3,22,2092.0,1,LAL,0,0,1,2
11,11,1,0,2012-10-30,5,11,6,Brandon,4,3,...,MIA,2,15,1699.0,0,BOS,0,0,11,1
12,12,5,0,2012-10-30,7,8,5,Tristan,4,2,...,WAS,2,12,1891.0,1,CLE,0,0,10,2
13,13,11,0,2012-10-30,1,7,3,Mario,2,2,...,BOS,3,8,2189.0,3,MIA,1,0,1,1
14,14,1,0,2012-10-30,1,8,6,Leandro,2,1,...,MIA,1,16,950.0,0,BOS,3,3,1,0
15,15,4,2,2012-10-30,2,8,3,Trevor,2,1,...,CLE,0,9,1475.0,3,WAS,4,2,3,0
16,16,0,3,2012-10-30,4,5,5,Brandan,5,4,...,LAL,3,14,1171.0,0,DAL,0,0,5,3
17,17,5,0,2012-10-30,0,8,4,Rodrigue,2,2,...,LAL,2,11,1010.0,1,DAL,2,1,1,0
18,18,2,1,2012-10-30,6,12,8,Dwight,14,3,...,DAL,6,19,2279.0,0,LAL,0,0,10,3
19,19,1,1,2012-10-30,5,5,4,Rashard,2,1,...,BOS,1,10,1135.0,0,MIA,2,1,5,0
20,20,0,1,2012-10-30,4,6,4,Earl,1,0,...,CLE,2,8,975.0,1,WAS,0,0,8,0
21,21,0,0,2012-10-30,2,14,6,Dion,4,3,...,WAS,0,17,1694.0,3,CLE,5,2,2,3
22,22,4,1,2012-10-30,7,11,5,Shawn,1,1,...,LAL,4,11,1973.0,1,DAL,0,0,9,2
23,23,1,0,2012-10-30,3,6,4,Martell,0,0,...,CLE,1,9,1405.0,2,WAS,3,1,3,0
24,24,0,4,2012-10-30,2,10,4,Emeka,4,2,...,CLE,1,10,1475.0,0,WAS,0,0,7,1
25,25,1,1,2012-10-30,2,5,3,Daniel,4,2,...,WAS,2,10,971.0,0,CLE,4,2,3,0
26,26,5,1,2012-10-30,2,13,4,Jordan,4,3,...,CLE,1,11,1722.0,1,WAS,6,0,3,1
27,27,2,1,2012-10-30,9,10,3,Elton,2,2,...,LAL,4,8,2172.0,1,DAL,0,0,11,0
28,28,2,0,2012-10-30,3,7,3,Jae,0,0,...,LAL,1,8,1170.0,1,DAL,4,2,3,0
29,29,1,0,2012-10-30,1,6,5,Courtney,0,0,...,MIA,5,11,1440.0,0,BOS,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19818,19818,2,0,2018-04-12,1,18,10,Gary,5,3,...,MIL,4,28,2366.0,1,DEN,7,5,1,4
19819,19819,1,1,2018-04-12,3,9,7,Tyler,0,0,...,DEN,3,14,1809.0,0,MIL,0,0,5,0
19820,19820,5,0,2018-04-12,2,14,6,Brandon,7,5,...,MIN,2,17,2024.0,0,LAL,2,0,4,2
19821,19821,4,2,2018-04-12,16,9,2,Karl-Anthony,6,6,...,LAL,4,10,1933.0,0,MIN,2,0,19,3
19822,19822,3,0,2018-04-12,0,11,6,Jamal,1,1,...,LAL,0,15,1321.0,0,MIN,6,2,0,1
19823,19823,0,0,2018-04-12,3,8,5,Jabari,1,1,...,DEN,0,12,996.0,1,MIL,2,1,5,1
19824,19824,2,0,2018-04-12,0,4,3,Tyus,0,0,...,LAL,2,8,791.0,2,MIN,3,2,1,0
19825,19825,0,2,2018-04-12,0,10,5,Trey,0,0,...,MIL,2,12,999.0,1,DEN,4,2,0,0
19826,19826,0,1,2018-04-12,6,17,7,Khris,3,2,...,DEN,4,17,2283.0,2,MIL,3,1,7,4
19827,19827,4,0,2018-04-12,1,6,2,Devin,0,0,...,MIL,0,6,1148.0,0,DEN,5,2,1,0
19828,19828,2,1,2018-04-12,4,9,4,Wilson,0,0,...,MIL,5,11,2258.0,1,DEN,5,3,4,3
19829,19829,0,1,2018-04-12,3,7,3,Gorgui,0,0,...,LAL,2,6,947.0,1,MIN,0,0,5,0
19830,19830,1,0,2018-04-12,1,6,3,Corey,0,0,...,MIN,3,6,804.0,1,LAL,0,0,2,0
19831,19831,0,0,2018-04-12,1,11,4,Tony,0,0,...,DEN,2,10,2022.0,1,MIL,6,2,1,0
19832,19832,0,0,2018-04-12,3,10,4,Josh,0,0,...,MIN,3,8,1878.0,1,LAL,3,0,4,0
19833,19833,3,0,2018-04-12,1,6,2,Thon,0,0,...,DEN,3,4,1035.0,0,MIL,3,0,3,0
19834,19834,0,0,2018-04-12,3,11,4,Andrew,0,0,...,LAL,1,8,1962.0,0,MIN,1,0,4,0
19835,19835,0,1,2018-04-12,2,5,2,Brook,0,0,...,MIN,4,6,1557.0,0,LAL,5,2,2,0
19836,19836,1,0,2018-04-12,5,4,1,Sterling,0,0,...,DEN,0,3,789.0,0,MIL,3,1,5,0
19837,19837,2,1,2018-04-12,0,1,0,Darrell,0,0,...,MIL,1,0,713.0,1,DEN,1,0,1,0
19838,19838,0,0,2018-04-12,0,1,1,Juan,0,0,...,MIL,0,2,50.0,0,DEN,0,0,0,0
19839,19839,3,1,2018-04-12,1,3,0,Nemanja,0,0,...,LAL,2,0,569.0,0,MIN,2,0,2,0
19840,19840,0,1,2018-04-12,2,12,3,Kyle,0,0,...,MIN,2,8,1117.0,0,LAL,9,2,2,1
19841,19841,0,0,2018-04-12,0,0,0,Xavier,0,0,...,DEN,0,0,36.0,0,MIL,0,0,0,0
19842,19842,0,0,2018-04-12,0,0,0,Marshall,0,0,...,DEN,0,0,36.0,0,MIL,0,0,0,0
19843,19843,0,0,2018-04-12,0,0,0,D.J.,0,0,...,DEN,0,0,36.0,0,MIL,0,0,0,0
19844,19844,0,0,2018-04-12,0,1,0,Malik,0,0,...,MIL,0,0,315.0,0,DEN,1,0,0,0
19845,19845,1,0,2018-04-12,0,2,0,Jason,0,0,...,DEN,4,0,554.0,0,MIL,1,0,0,0
19846,19846,0,0,2018-04-12,0,0,0,Sean,0,0,...,DEN,1,0,246.0,0,MIL,0,0,0,2
19847,19847,5,1,2018-04-12,1,15,3,Isaiah,1,1,...,MIN,2,7,1492.0,0,LAL,5,0,1,5

In [11]:
season_stats = pd.read_csv('2012_2017_season_player_stats.csv', index_col=0)
season_stats.columns

Index([u'age', u'assists', u'blocks', u'defensive_rebounds',
       u'field_goals_attempted', u'field_goals_made', u'first_name',
       u'free_throws_attempted', u'free_throws_made', u'games_played',
       u'games_started', u'last_name', u'minutes_played',
       u'offensive_rebounds', u'personal_fouls', u'points', u'position',
       u'steals', u'team', u'three_point_field_goals_attempted',
       u'three_point_field_goals_made', u'turnovers',
       u'two_point_field_goals_attempted', u'two_point_field_goals_made',
       u'year'],
      dtype='object')

In [ ]:
X, Y = [], []
# put all played games into model
for i, row in played_schedule.iterrows():

In [ ]:
#Notes for regression:
# x_train = list of lists (interior list is all of features) - features should be numbers
# y_train = list of results (0-loss or 1-win)
# feature generation - creating x_train and y_train
# plug in and chug 5 lines code almost
# Make sure x_train and y_train are same length

# Tasks: 
# (1) create initial list of variables that thought to be important (8-25 variables - choose easiest first)
# (2) create the interior lists of x-train - one for each game and which games chosen dependent on current perspective
# (3) create the corresponding y-train (0,1) - basically in same order whether game chosen in x-train won or loss
# (4) plug in and chug once x-train and y-train completed

# Methods/Approaches - (1) PCA/SVM (2) Random Forest (3) Linear Regression - within each, can tweak parameters
# test model on subset of data that was not put into x-train - testtrainsplit() function arbitrarily picks values 
# for x-test and y-test and for train model (model.fit()) and 
# then use remaining values not used are used for model.predict()

# Predict point spread potentially

# start out with generic features - team stats first 
# individual stats would have to go into box scores and check/iterate through who played in those game
# historical team performances vs away/home 
# account for collinearity 

# have 3 models that work that have about 60-70% or higher (have at least one to)