In [1]:
import basketball_reference_web_scraper.readers as br
import pandas as pd
import ast 
import json

In [2]:
twelve = br.return_json_encoded_schedule(2012)

INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2013_games-october.html
/Users/NateXie/anaconda/envs/okcenv/lib/python2.7/site-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 174 of the file /Users/NateXie/anaconda/envs/okcenv/lib/python2.7/runpy.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup(YOUR_MARKUP})

to this:

 BeautifulSoup(YOUR_MARKUP, "lxml")

  markup_type=markup_type))
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2013_games-november.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2013_games-december.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2013_games-january.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2013_games-february.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2013_games-march.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2013_games-april.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2013_games-may.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2013_games-june.html

In [3]:
final_twelve = ast.literal_eval(twelve)['parsed_event_list']
with open('twelve.json', 'a') as _f:
    _f.write(json.dumps(final_twelve) + '\n')

In [4]:
loaded_twelve = []
with open('twelve.json', 'r') as _f:
    loaded_schedule = json.load(_f)
    for game in loaded_schedule:
        loaded_twelve.append(ast.literal_eval(game))

In [5]:
df_twelve = pd.DataFrame(loaded_twelve)
df_twelve['start_time'] = pd.to_datetime(df_twelve['start_time'])
df_twelve.head()

,home_team_name,home_team_score,start_time,visiting_team_name,visiting_team_score
0,Cleveland Cavaliers,94,2012-10-30 23:00:00,Washington Wizards,84
1,Los Angeles Lakers,91,2012-10-30 23:30:00,Dallas Mavericks,99
2,Miami Heat,120,2012-10-31 00:00:00,Boston Celtics,107
3,Chicago Bulls,93,2012-10-31 23:00:00,Sacramento Kings,87
4,Detroit Pistons,96,2012-10-31 23:30:00,Houston Rockets,105

In [7]:
twelve_unique_dates = df_twelve['start_time'].map(lambda t:t.date()).unique()
print(twelve_unique_dates)

[datetime.date(2012, 10, 30) datetime.date(2012, 10, 31)
 datetime.date(2012, 11, 2) datetime.date(2012, 11, 3)
 datetime.date(2012, 11, 4) datetime.date(2012, 11, 6)
 datetime.date(2012, 11, 7) datetime.date(2012, 11, 8)
 datetime.date(2012, 11, 9) datetime.date(2012, 11, 10)
 datetime.date(2012, 11, 11) datetime.date(2012, 11, 13)
 datetime.date(2012, 11, 14) datetime.date(2012, 11, 15)
 datetime.date(2012, 11, 16) datetime.date(2012, 11, 17)
 datetime.date(2012, 11, 18) datetime.date(2012, 11, 19)
 datetime.date(2012, 11, 20) datetime.date(2012, 11, 21)
 datetime.date(2012, 11, 22) datetime.date(2012, 11, 24)
 datetime.date(2012, 11, 25) datetime.date(2012, 11, 27)
 datetime.date(2012, 11, 28) datetime.date(2012, 11, 29)
 datetime.date(2012, 11, 30) datetime.date(2012, 12, 1)
 datetime.date(2012, 12, 2) datetime.date(2012, 12, 4)
 datetime.date(2012, 12, 5) datetime.date(2012, 12, 6)
 datetime.date(2012, 12, 7) datetime.date(2012, 12, 8)
 datetime.date(2012, 12, 9) datetime.date(2012, 12, 10)
 datetime.date(2012, 12, 11) datetime.date(2012, 12, 12)
 datetime.date(2012, 12, 13) datetime.date(2012, 12, 14)
 datetime.date(2012, 12, 15) datetime.date(2012, 12, 16)
 datetime.date(2012, 12, 18) datetime.date(2012, 12, 19)
 datetime.date(2012, 12, 20) datetime.date(2012, 12, 21)
 datetime.date(2012, 12, 22) datetime.date(2012, 12, 23)
 datetime.date(2012, 12, 25) datetime.date(2012, 12, 26)
 datetime.date(2012, 12, 27) datetime.date(2012, 12, 28)
 datetime.date(2012, 12, 29) datetime.date(2012, 12, 30)
 datetime.date(2012, 12, 31) datetime.date(2013, 1, 1)
 datetime.date(2013, 1, 2) datetime.date(2013, 1, 3)
 datetime.date(2013, 1, 4) datetime.date(2013, 1, 5)
 datetime.date(2013, 1, 6) datetime.date(2013, 1, 7)
 datetime.date(2013, 1, 8) datetime.date(2013, 1, 9)
 datetime.date(2013, 1, 10) datetime.date(2013, 1, 11)
 datetime.date(2013, 1, 12) datetime.date(2013, 1, 13)
 datetime.date(2013, 1, 15) datetime.date(2013, 1, 16)
 datetime.date(2013, 1, 17) datetime.date(2013, 1, 18)
 datetime.date(2013, 1, 19) datetime.date(2013, 1, 20)
 datetime.date(2013, 1, 21) datetime.date(2013, 1, 22)
 datetime.date(2013, 1, 23) datetime.date(2013, 1, 24)
 datetime.date(2013, 1, 25) datetime.date(2013, 1, 26)
 datetime.date(2013, 1, 27) datetime.date(2013, 1, 29)
 datetime.date(2013, 1, 30) datetime.date(2013, 1, 31)
 datetime.date(2013, 2, 1) datetime.date(2013, 2, 2)
 datetime.date(2013, 2, 3) datetime.date(2013, 2, 5)
 datetime.date(2013, 2, 6) datetime.date(2013, 2, 7)
 datetime.date(2013, 2, 8) datetime.date(2013, 2, 9)
 datetime.date(2013, 2, 10) datetime.date(2013, 2, 11)
 datetime.date(2013, 2, 12) datetime.date(2013, 2, 13)
 datetime.date(2013, 2, 14) datetime.date(2013, 2, 15)
 datetime.date(2013, 2, 20) datetime.date(2013, 2, 21)
 datetime.date(2013, 2, 22) datetime.date(2013, 2, 23)
 datetime.date(2013, 2, 24) datetime.date(2013, 2, 25)
 datetime.date(2013, 2, 26) datetime.date(2013, 2, 27)
 datetime.date(2013, 2, 28) datetime.date(2013, 3, 1)
 datetime.date(2013, 3, 2) datetime.date(2013, 3, 3)
 datetime.date(2013, 3, 4) datetime.date(2013, 3, 5)
 datetime.date(2013, 3, 6) datetime.date(2013, 3, 7)
 datetime.date(2013, 3, 8) datetime.date(2013, 3, 9)
 datetime.date(2013, 3, 10) datetime.date(2013, 3, 11)
 datetime.date(2013, 3, 12) datetime.date(2013, 3, 13)
 datetime.date(2013, 3, 14) datetime.date(2013, 3, 15)
 datetime.date(2013, 3, 16) datetime.date(2013, 3, 17)
 datetime.date(2013, 3, 18) datetime.date(2013, 3, 19)
 datetime.date(2013, 3, 20) datetime.date(2013, 3, 21)
 datetime.date(2013, 3, 22) datetime.date(2013, 3, 23)
 datetime.date(2013, 3, 24) datetime.date(2013, 3, 25)
 datetime.date(2013, 3, 26) datetime.date(2013, 3, 27)
 datetime.date(2013, 3, 28) datetime.date(2013, 3, 29)
 datetime.date(2013, 3, 30) datetime.date(2013, 3, 31)
 datetime.date(2013, 4, 1) datetime.date(2013, 4, 2)
 datetime.date(2013, 4, 3) datetime.date(2013, 4, 4)
 datetime.date(2013, 4, 5) datetime.date(2013, 4, 6)
 datetime.date(2013, 4, 7) datetime.date(2013, 4, 9)
 datetime.date(2013, 4, 11) datetime.date(2013, 4, 10)
 datetime.date(2013, 4, 12) datetime.date(2013, 4, 13)
 datetime.date(2013, 4, 14) datetime.date(2013, 4, 15)
 datetime.date(2013, 4, 17) datetime.date(2013, 4, 16)
 datetime.date(2013, 4, 18) datetime.date(2013, 4, 21)
 datetime.date(2013, 4, 20) datetime.date(2013, 4, 22)
 datetime.date(2013, 4, 23) datetime.date(2013, 4, 24)
 datetime.date(2013, 4, 25) datetime.date(2013, 4, 26)
 datetime.date(2013, 4, 27) datetime.date(2013, 4, 28)
 datetime.date(2013, 4, 29) datetime.date(2013, 4, 30)
 datetime.date(2013, 5, 1) datetime.date(2013, 5, 2)
 datetime.date(2013, 5, 3) datetime.date(2013, 5, 4)
 datetime.date(2013, 5, 5) datetime.date(2013, 5, 6)
 datetime.date(2013, 5, 7) datetime.date(2013, 5, 8)
 datetime.date(2013, 5, 9) datetime.date(2013, 5, 11)
 datetime.date(2013, 5, 12) datetime.date(2013, 5, 13)
 datetime.date(2013, 5, 14) datetime.date(2013, 5, 15)
 datetime.date(2013, 5, 16) datetime.date(2013, 5, 17)
 datetime.date(2013, 5, 19) datetime.date(2013, 5, 22)
 datetime.date(2013, 5, 23) datetime.date(2013, 5, 25)
 datetime.date(2013, 5, 26) datetime.date(2013, 5, 27)
 datetime.date(2013, 5, 28) datetime.date(2013, 5, 29)
 datetime.date(2013, 5, 31) datetime.date(2013, 6, 2)
 datetime.date(2013, 6, 4) datetime.date(2013, 6, 7)
 datetime.date(2013, 6, 10) datetime.date(2013, 6, 12)
 datetime.date(2013, 6, 14) datetime.date(2013, 6, 17)
 datetime.date(2013, 6, 19) datetime.date(2013, 6, 21)]

In [8]:
df_twelve.to_csv('2012_schedule.csv')

In [9]:
pd.read_csv('2012_schedule.csv', index_col=0)

,home_team_name,home_team_score,start_time,visiting_team_name,visiting_team_score
0,Cleveland Cavaliers,94,2012-10-30 23:00:00,Washington Wizards,84
1,Los Angeles Lakers,91,2012-10-30 23:30:00,Dallas Mavericks,99
2,Miami Heat,120,2012-10-31 00:00:00,Boston Celtics,107
3,Chicago Bulls,93,2012-10-31 23:00:00,Sacramento Kings,87
4,Detroit Pistons,96,2012-10-31 23:30:00,Houston Rockets,105
5,Los Angeles Clippers,101,2012-10-31 23:30:00,Memphis Grizzlies,92
6,New Orleans Hornets,95,2012-10-31 23:00:00,San Antonio Spurs,99
7,Philadelphia 76ers,84,2012-10-31 23:00:00,Denver Nuggets,75
8,Phoenix Suns,85,2012-10-31 23:00:00,Golden State Warriors,87
9,Portland Trail Blazers,116,2012-10-31 23:30:00,Los Angeles Lakers,106
10,Toronto Raptors,88,2012-10-31 23:00:00,Indiana Pacers,90
11,Utah Jazz,113,2012-10-31 23:00:00,Dallas Mavericks,94
12,San Antonio Spurs,86,2012-11-02 00:30:00,Oklahoma City Thunder,84
13,Atlanta Hawks,102,2012-11-02 23:30:00,Houston Rockets,109
14,Boston Celtics,88,2012-11-02 23:30:00,Milwaukee Bucks,99
15,Charlotte Bobcats,90,2012-11-02 23:00:00,Indiana Pacers,89
16,Cleveland Cavaliers,86,2012-11-02 23:30:00,Chicago Bulls,115
17,Golden State Warriors,94,2012-11-02 23:30:00,Memphis Grizzlies,104
18,Los Angeles Lakers,95,2012-11-02 23:30:00,Los Angeles Clippers,105
19,Minnesota Timberwolves,92,2012-11-02 23:00:00,Sacramento Kings,80
20,New Orleans Hornets,88,2012-11-02 23:00:00,Utah Jazz,86
21,New York Knicks,104,2012-11-03 00:00:00,Miami Heat,84
22,Oklahoma City Thunder,106,2012-11-02 23:00:00,Portland Trail Blazers,92
23,Orlando Magic,102,2012-11-02 23:00:00,Denver Nuggets,89
24,Phoenix Suns,92,2012-11-02 23:00:00,Detroit Pistons,89
25,Brooklyn Nets,107,2012-11-03 23:30:00,Toronto Raptors,100
26,Chicago Bulls,82,2012-11-03 23:00:00,New Orleans Hornets,89
27,Dallas Mavericks,126,2012-11-03 23:30:00,Charlotte Bobcats,99
28,Houston Rockets,85,2012-11-03 23:00:00,Portland Trail Blazers,95
29,Indiana Pacers,106,2012-11-03 23:00:00,Sacramento Kings,98
...,...,...,...,...,...
1284,Indiana Pacers,82,2013-05-12 00:00:00,New York Knicks,71
1285,Memphis Grizzlies,87,2013-05-11 21:00:00,Oklahoma City Thunder,81
1286,Golden State Warriors,97,2013-05-12 19:30:00,San Antonio Spurs,87
1287,Chicago Bulls,65,2013-05-13 23:00:00,Miami Heat,88
1288,Memphis Grizzlies,103,2013-05-14 01:30:00,Oklahoma City Thunder,97
1289,Indiana Pacers,93,2013-05-14 23:00:00,New York Knicks,82
1290,San Antonio Spurs,109,2013-05-15 01:30:00,Golden State Warriors,91
1291,Miami Heat,94,2013-05-15 23:00:00,Chicago Bulls,91
1292,Oklahoma City Thunder,84,2013-05-16 01:30:00,Memphis Grizzlies,88
1293,Golden State Warriors,82,2013-05-17 02:30:00,San Antonio Spurs,94
1294,New York Knicks,85,2013-05-17 00:00:00,Indiana Pacers,75
1295,Indiana Pacers,106,2013-05-19 00:00:00,New York Knicks,99
1296,San Antonio Spurs,105,2013-05-19 19:30:00,Memphis Grizzlies,83
1297,San Antonio Spurs,93,2013-05-22 01:00:00,Memphis Grizzlies,89
1298,Miami Heat,103,2013-05-23 00:30:00,Indiana Pacers,102
1299,Miami Heat,93,2013-05-25 00:30:00,Indiana Pacers,97
1300,Memphis Grizzlies,93,2013-05-26 01:00:00,San Antonio Spurs,104
1301,Indiana Pacers,96,2013-05-27 00:30:00,Miami Heat,114
1302,Memphis Grizzlies,86,2013-05-28 01:00:00,San Antonio Spurs,93
1303,Indiana Pacers,99,2013-05-29 00:30:00,Miami Heat,92
1304,Miami Heat,90,2013-05-31 00:30:00,Indiana Pacers,79
1305,Indiana Pacers,91,2013-06-02 00:30:00,Miami Heat,77
1306,Miami Heat,99,2013-06-04 00:30:00,Indiana Pacers,76
1307,Miami Heat,88,2013-06-07 01:00:00,San Antonio Spurs,92
1308,Miami Heat,103,2013-06-10 00:00:00,San Antonio Spurs,84
1309,San Antonio Spurs,113,2013-06-12 01:00:00,Miami Heat,77
1310,San Antonio Spurs,93,2013-06-14 01:00:00,Miami Heat,109
1311,San Antonio Spurs,114,2013-06-17 00:00:00,Miami Heat,104
1312,Miami Heat,103,2013-06-19 01:00:00,San Antonio Spurs,100
1313,Miami Heat,95,2013-06-21 01:00:00,San Antonio Spurs,88

In [10]:
thirteen = br.return_json_encoded_schedule(2013)

INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2014_games-october.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2014_games-november.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2014_games-december.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2014_games-january.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2014_games-february.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2014_games-march.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2014_games-april.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2014_games-may.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2014_games-june.html

In [12]:
final_thirteen = ast.literal_eval(thirteen)['parsed_event_list']
with open('thirteen.json','a') as _g:
    _g.write(json.dumps(final_thirteen) + '\n')

In [13]:
loaded_thirteen = []
with open('thirteen.json', 'r') as _g:
    loaded_schedule = json.load(_g)
    for game in loaded_schedule:
        loaded_thirteen.append(ast.literal_eval(game))

In [14]:
df_thirteen = pd.DataFrame(loaded_thirteen)
df_thirteen['start_time'] = pd.to_datetime(df_thirteen['start_time'])
df_thirteen.head()

,home_team_name,home_team_score,start_time,visiting_team_name,visiting_team_score
0,Indiana Pacers,97,2013-10-29 23:00:00,Orlando Magic,87
1,Los Angeles Lakers,116,2013-10-30 02:30:00,Los Angeles Clippers,103
2,Miami Heat,107,2013-10-30 00:00:00,Chicago Bulls,95
3,Cleveland Cavaliers,98,2013-10-30 23:00:00,Brooklyn Nets,94
4,Dallas Mavericks,118,2013-10-31 00:30:00,Atlanta Hawks,109

In [15]:
thirteen_unique_dates = df_thirteen['start_time'].map(lambda t: t.date()).unique()
print(thirteen_unique_dates)

[datetime.date(2013, 10, 29) datetime.date(2013, 10, 30)
 datetime.date(2013, 10, 31) datetime.date(2013, 11, 1)
 datetime.date(2013, 11, 2) datetime.date(2013, 11, 3)
 datetime.date(2013, 11, 4) datetime.date(2013, 11, 5)
 datetime.date(2013, 11, 6) datetime.date(2013, 11, 7)
 datetime.date(2013, 11, 8) datetime.date(2013, 11, 9)
 datetime.date(2013, 11, 10) datetime.date(2013, 11, 11)
 datetime.date(2013, 11, 12) datetime.date(2013, 11, 13)
 datetime.date(2013, 11, 14) datetime.date(2013, 11, 15)
 datetime.date(2013, 11, 16) datetime.date(2013, 11, 17)
 datetime.date(2013, 11, 18) datetime.date(2013, 11, 19)
 datetime.date(2013, 11, 20) datetime.date(2013, 11, 21)
 datetime.date(2013, 11, 22) datetime.date(2013, 11, 23)
 datetime.date(2013, 11, 24) datetime.date(2013, 11, 25)
 datetime.date(2013, 11, 26) datetime.date(2013, 11, 27)
 datetime.date(2013, 11, 28) datetime.date(2013, 11, 30)
 datetime.date(2013, 12, 1) datetime.date(2013, 12, 2)
 datetime.date(2013, 12, 3) datetime.date(2013, 12, 4)
 datetime.date(2013, 12, 5) datetime.date(2013, 12, 6)
 datetime.date(2013, 12, 7) datetime.date(2013, 12, 8)
 datetime.date(2013, 12, 9) datetime.date(2013, 12, 10)
 datetime.date(2013, 12, 11) datetime.date(2013, 12, 12)
 datetime.date(2013, 12, 13) datetime.date(2013, 12, 14)
 datetime.date(2013, 12, 15) datetime.date(2013, 12, 16)
 datetime.date(2013, 12, 17) datetime.date(2013, 12, 18)
 datetime.date(2013, 12, 19) datetime.date(2013, 12, 20)
 datetime.date(2013, 12, 21) datetime.date(2013, 12, 22)
 datetime.date(2013, 12, 23) datetime.date(2013, 12, 24)
 datetime.date(2013, 12, 25) datetime.date(2013, 12, 26)
 datetime.date(2013, 12, 27) datetime.date(2013, 12, 28)
 datetime.date(2013, 12, 29) datetime.date(2013, 12, 30)
 datetime.date(2013, 12, 31) datetime.date(2014, 1, 1)
 datetime.date(2014, 1, 2) datetime.date(2014, 1, 3)
 datetime.date(2014, 1, 4) datetime.date(2014, 1, 5)
 datetime.date(2014, 1, 6) datetime.date(2014, 1, 7)
 datetime.date(2014, 1, 8) datetime.date(2014, 1, 9)
 datetime.date(2014, 1, 10) datetime.date(2014, 1, 11)
 datetime.date(2014, 1, 12) datetime.date(2014, 1, 13)
 datetime.date(2014, 1, 14) datetime.date(2014, 1, 15)
 datetime.date(2014, 1, 16) datetime.date(2014, 1, 17)
 datetime.date(2014, 1, 18) datetime.date(2014, 1, 19)
 datetime.date(2014, 1, 20) datetime.date(2014, 1, 21)
 datetime.date(2014, 1, 22) datetime.date(2014, 1, 23)
 datetime.date(2014, 1, 24) datetime.date(2014, 1, 25)
 datetime.date(2014, 1, 26) datetime.date(2014, 1, 27)
 datetime.date(2014, 1, 28) datetime.date(2014, 1, 29)
 datetime.date(2014, 1, 30) datetime.date(2014, 1, 31)
 datetime.date(2014, 2, 1) datetime.date(2014, 2, 2)
 datetime.date(2014, 2, 4) datetime.date(2014, 2, 5)
 datetime.date(2014, 2, 6) datetime.date(2014, 2, 7)
 datetime.date(2014, 2, 8) datetime.date(2014, 2, 9)
 datetime.date(2014, 2, 10) datetime.date(2014, 2, 11)
 datetime.date(2014, 2, 12) datetime.date(2014, 2, 13)
 datetime.date(2014, 2, 14) datetime.date(2014, 2, 19)
 datetime.date(2014, 2, 20) datetime.date(2014, 2, 21)
 datetime.date(2014, 2, 22) datetime.date(2014, 2, 23)
 datetime.date(2014, 2, 24) datetime.date(2014, 2, 25)
 datetime.date(2014, 2, 26) datetime.date(2014, 2, 27)
 datetime.date(2014, 2, 28) datetime.date(2014, 3, 1)
 datetime.date(2014, 3, 2) datetime.date(2014, 3, 3)
 datetime.date(2014, 3, 4) datetime.date(2014, 3, 5)
 datetime.date(2014, 3, 6) datetime.date(2014, 3, 7)
 datetime.date(2014, 3, 8) datetime.date(2014, 3, 9)
 datetime.date(2014, 3, 10) datetime.date(2014, 3, 11)
 datetime.date(2014, 3, 12) datetime.date(2014, 3, 13)
 datetime.date(2014, 3, 14) datetime.date(2014, 3, 15)
 datetime.date(2014, 3, 16) datetime.date(2014, 3, 17)
 datetime.date(2014, 3, 18) datetime.date(2014, 3, 19)
 datetime.date(2014, 3, 20) datetime.date(2014, 3, 21)
 datetime.date(2014, 3, 22) datetime.date(2014, 3, 23)
 datetime.date(2014, 3, 24) datetime.date(2014, 3, 25)
 datetime.date(2014, 3, 26) datetime.date(2014, 3, 27)
 datetime.date(2014, 3, 28) datetime.date(2014, 3, 29)
 datetime.date(2014, 3, 30) datetime.date(2014, 3, 31)
 datetime.date(2014, 4, 1) datetime.date(2014, 4, 2)
 datetime.date(2014, 4, 3) datetime.date(2014, 4, 4)
 datetime.date(2014, 4, 5) datetime.date(2014, 4, 6)
 datetime.date(2014, 4, 7) datetime.date(2014, 4, 8)
 datetime.date(2014, 4, 9) datetime.date(2014, 4, 10)
 datetime.date(2014, 4, 11) datetime.date(2014, 4, 12)
 datetime.date(2014, 4, 13) datetime.date(2014, 4, 14)
 datetime.date(2014, 4, 15) datetime.date(2014, 4, 16)
 datetime.date(2014, 4, 17) datetime.date(2014, 4, 19)
 datetime.date(2014, 4, 20) datetime.date(2014, 4, 21)
 datetime.date(2014, 4, 22) datetime.date(2014, 4, 23)
 datetime.date(2014, 4, 24) datetime.date(2014, 4, 25)
 datetime.date(2014, 4, 26) datetime.date(2014, 4, 27)
 datetime.date(2014, 4, 28) datetime.date(2014, 4, 29)
 datetime.date(2014, 4, 30) datetime.date(2014, 5, 1)
 datetime.date(2014, 5, 2) datetime.date(2014, 5, 3)
 datetime.date(2014, 5, 4) datetime.date(2014, 5, 5)
 datetime.date(2014, 5, 6) datetime.date(2014, 5, 7)
 datetime.date(2014, 5, 8) datetime.date(2014, 5, 9)
 datetime.date(2014, 5, 10) datetime.date(2014, 5, 11)
 datetime.date(2014, 5, 12) datetime.date(2014, 5, 13)
 datetime.date(2014, 5, 14) datetime.date(2014, 5, 15)
 datetime.date(2014, 5, 16) datetime.date(2014, 5, 18)
 datetime.date(2014, 5, 20) datetime.date(2014, 5, 21)
 datetime.date(2014, 5, 22) datetime.date(2014, 5, 25)
 datetime.date(2014, 5, 26) datetime.date(2014, 5, 27)
 datetime.date(2014, 5, 28) datetime.date(2014, 5, 29)
 datetime.date(2014, 5, 30) datetime.date(2014, 5, 31)
 datetime.date(2014, 6, 1) datetime.date(2014, 6, 6)
 datetime.date(2014, 6, 9) datetime.date(2014, 6, 11)
 datetime.date(2014, 6, 13) datetime.date(2014, 6, 16)]

In [16]:
df_thirteen.to_csv('2013_schedule.csv')

In [17]:
pd.read_csv('2013_schedule.csv', index_col=0)

,home_team_name,home_team_score,start_time,visiting_team_name,visiting_team_score
0,Indiana Pacers,97,2013-10-29 23:00:00,Orlando Magic,87
1,Los Angeles Lakers,116,2013-10-30 02:30:00,Los Angeles Clippers,103
2,Miami Heat,107,2013-10-30 00:00:00,Chicago Bulls,95
3,Cleveland Cavaliers,98,2013-10-30 23:00:00,Brooklyn Nets,94
4,Dallas Mavericks,118,2013-10-31 00:30:00,Atlanta Hawks,109
5,Detroit Pistons,113,2013-10-30 23:30:00,Washington Wizards,102
6,Golden State Warriors,125,2013-10-31 02:30:00,Los Angeles Lakers,94
7,Houston Rockets,96,2013-10-31 00:00:00,Charlotte Bobcats,83
8,Minnesota Timberwolves,120,2013-10-31 00:00:00,Orlando Magic,115
9,New Orleans Pelicans,90,2013-10-31 00:00:00,Indiana Pacers,95
10,New York Knicks,90,2013-10-30 23:30:00,Milwaukee Bucks,83
11,Philadelphia 76ers,114,2013-10-30 23:00:00,Miami Heat,110
12,Phoenix Suns,104,2013-10-31 02:00:00,Portland Trail Blazers,91
13,Sacramento Kings,90,2013-10-31 02:00:00,Denver Nuggets,88
14,San Antonio Spurs,101,2013-10-31 00:30:00,Memphis Grizzlies,94
15,Toronto Raptors,93,2013-10-30 23:00:00,Boston Celtics,87
16,Utah Jazz,98,2013-10-31 01:00:00,Oklahoma City Thunder,101
17,Chicago Bulls,82,2013-11-01 00:00:00,New York Knicks,81
18,Los Angeles Clippers,126,2013-11-01 02:30:00,Golden State Warriors,115
19,Atlanta Hawks,102,2013-11-01 23:30:00,Toronto Raptors,95
20,Boston Celtics,98,2013-11-01 23:30:00,Milwaukee Bucks,105
21,Brooklyn Nets,101,2013-11-02 00:00:00,Miami Heat,100
22,Charlotte Bobcats,90,2013-11-01 23:00:00,Cleveland Cavaliers,84
23,Denver Nuggets,98,2013-11-02 01:00:00,Portland Trail Blazers,113
24,Houston Rockets,113,2013-11-02 00:00:00,Dallas Mavericks,105
25,Los Angeles Lakers,85,2013-11-02 02:30:00,San Antonio Spurs,91
26,Memphis Grizzlies,111,2013-11-02 00:00:00,Detroit Pistons,108
27,Minnesota Timberwolves,100,2013-11-02 00:00:00,Oklahoma City Thunder,81
28,Orlando Magic,110,2013-11-01 23:00:00,New Orleans Pelicans,90
29,Phoenix Suns,87,2013-11-02 02:00:00,Utah Jazz,84
...,...,...,...,...,...
1289,Washington Wizards,63,2014-05-10 00:00:00,Indiana Pacers,85
1290,Brooklyn Nets,104,2014-05-11 00:00:00,Miami Heat,90
1291,Portland Trail Blazers,103,2014-05-11 02:30:00,San Antonio Spurs,118
1292,Los Angeles Clippers,101,2014-05-11 19:30:00,Oklahoma City Thunder,99
1293,Washington Wizards,92,2014-05-12 00:00:00,Indiana Pacers,95
1294,Brooklyn Nets,96,2014-05-13 00:00:00,Miami Heat,102
1295,Portland Trail Blazers,103,2014-05-13 02:30:00,San Antonio Spurs,92
1296,Indiana Pacers,79,2014-05-13 23:00:00,Washington Wizards,102
1297,Oklahoma City Thunder,105,2014-05-14 01:30:00,Los Angeles Clippers,104
1298,Miami Heat,96,2014-05-14 23:00:00,Brooklyn Nets,94
1299,San Antonio Spurs,104,2014-05-15 01:30:00,Portland Trail Blazers,82
1300,Los Angeles Clippers,98,2014-05-16 02:30:00,Oklahoma City Thunder,104
1301,Washington Wizards,80,2014-05-16 00:00:00,Indiana Pacers,93
1302,Indiana Pacers,107,2014-05-18 19:30:00,Miami Heat,96
1303,San Antonio Spurs,122,2014-05-20 01:00:00,Oklahoma City Thunder,105
1304,Indiana Pacers,83,2014-05-21 00:30:00,Miami Heat,87
1305,San Antonio Spurs,112,2014-05-22 01:00:00,Oklahoma City Thunder,77
1306,Miami Heat,99,2014-05-25 00:30:00,Indiana Pacers,87
1307,Oklahoma City Thunder,106,2014-05-26 00:30:00,San Antonio Spurs,97
1308,Miami Heat,102,2014-05-27 00:30:00,Indiana Pacers,90
1309,Oklahoma City Thunder,105,2014-05-28 01:00:00,San Antonio Spurs,92
1310,Indiana Pacers,93,2014-05-29 00:30:00,Miami Heat,90
1311,San Antonio Spurs,117,2014-05-30 01:00:00,Oklahoma City Thunder,89
1312,Miami Heat,117,2014-05-31 00:30:00,Indiana Pacers,92
1313,Oklahoma City Thunder,107,2014-06-01 00:30:00,San Antonio Spurs,112
1314,San Antonio Spurs,110,2014-06-06 01:00:00,Miami Heat,95
1315,San Antonio Spurs,96,2014-06-09 00:00:00,Miami Heat,98
1316,Miami Heat,92,2014-06-11 01:00:00,San Antonio Spurs,111
1317,Miami Heat,86,2014-06-13 01:00:00,San Antonio Spurs,107
1318,San Antonio Spurs,104,2014-06-16 00:00:00,Miami Heat,87

In [19]:
fourteen = br.return_json_encoded_schedule(2014)

INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2015_games-october.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2015_games-november.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2015_games-december.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2015_games-january.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2015_games-february.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2015_games-march.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2015_games-april.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2015_games-may.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2015_games-june.html

In [24]:
final_fourteen = ast.literal_eval(fourteen)['parsed_event_list']
with open('fourteen.json','a') as _h:
    _h.write(json.dumps(final_fourteen) + '\n')

In [25]:
loaded_fourteen = []
with open('fourteen.json', 'r') as _h:
    loaded_schedule = json.load(_h)
    for game in loaded_schedule:
        loaded_fourteen.append(ast.literal_eval(game))

In [26]:
df_fourteen = pd.DataFrame(loaded_fourteen)
df_fourteen['start_time'] = pd.to_datetime(df_fourteen['start_time'])
df_fourteen.head()

,home_team_name,home_team_score,start_time,visiting_team_name,visiting_team_score
0,Los Angeles Lakers,90,2014-10-29 02:30:00,Houston Rockets,108
1,New Orleans Pelicans,101,2014-10-29 00:00:00,Orlando Magic,84
2,San Antonio Spurs,101,2014-10-29 00:00:00,Dallas Mavericks,100
3,Boston Celtics,121,2014-10-29 23:30:00,Brooklyn Nets,105
4,Charlotte Hornets,108,2014-10-29 23:00:00,Milwaukee Bucks,106

In [27]:
fourteen_unique_dates = df_fourteen['start_time'].map(lambda t: t.date()).unique()
print(fourteen_unique_dates)

[datetime.date(2014, 10, 29) datetime.date(2014, 10, 30)
 datetime.date(2014, 10, 31) datetime.date(2014, 11, 1)
 datetime.date(2014, 11, 2) datetime.date(2014, 11, 3)
 datetime.date(2014, 11, 4) datetime.date(2014, 11, 5)
 datetime.date(2014, 11, 6) datetime.date(2014, 11, 7)
 datetime.date(2014, 11, 8) datetime.date(2014, 11, 9)
 datetime.date(2014, 11, 10) datetime.date(2014, 11, 11)
 datetime.date(2014, 11, 12) datetime.date(2014, 11, 13)
 datetime.date(2014, 11, 14) datetime.date(2014, 11, 15)
 datetime.date(2014, 11, 16) datetime.date(2014, 11, 17)
 datetime.date(2014, 11, 18) datetime.date(2014, 11, 19)
 datetime.date(2014, 11, 20) datetime.date(2014, 11, 21)
 datetime.date(2014, 11, 22) datetime.date(2014, 11, 23)
 datetime.date(2014, 11, 24) datetime.date(2014, 11, 25)
 datetime.date(2014, 11, 26) datetime.date(2014, 11, 27)
 datetime.date(2014, 11, 29) datetime.date(2014, 11, 28)
 datetime.date(2014, 11, 30) datetime.date(2014, 12, 1)
 datetime.date(2014, 12, 2) datetime.date(2014, 12, 3)
 datetime.date(2014, 12, 4) datetime.date(2014, 12, 5)
 datetime.date(2014, 12, 6) datetime.date(2014, 12, 7)
 datetime.date(2014, 12, 8) datetime.date(2014, 12, 9)
 datetime.date(2014, 12, 10) datetime.date(2014, 12, 11)
 datetime.date(2014, 12, 12) datetime.date(2014, 12, 13)
 datetime.date(2014, 12, 14) datetime.date(2014, 12, 15)
 datetime.date(2014, 12, 16) datetime.date(2014, 12, 17)
 datetime.date(2014, 12, 18) datetime.date(2014, 12, 19)
 datetime.date(2014, 12, 20) datetime.date(2014, 12, 21)
 datetime.date(2014, 12, 22) datetime.date(2014, 12, 23)
 datetime.date(2014, 12, 24) datetime.date(2014, 12, 26)
 datetime.date(2014, 12, 25) datetime.date(2014, 12, 27)
 datetime.date(2014, 12, 28) datetime.date(2014, 12, 29)
 datetime.date(2014, 12, 30) datetime.date(2014, 12, 31)
 datetime.date(2015, 1, 1) datetime.date(2015, 1, 2)
 datetime.date(2015, 1, 3) datetime.date(2015, 1, 4)
 datetime.date(2015, 1, 5) datetime.date(2015, 1, 6)
 datetime.date(2015, 1, 7) datetime.date(2015, 1, 8)
 datetime.date(2015, 1, 9) datetime.date(2015, 1, 10)
 datetime.date(2015, 1, 11) datetime.date(2015, 1, 12)
 datetime.date(2015, 1, 13) datetime.date(2015, 1, 14)
 datetime.date(2015, 1, 15) datetime.date(2015, 1, 16)
 datetime.date(2015, 1, 17) datetime.date(2015, 1, 18)
 datetime.date(2015, 1, 19) datetime.date(2015, 1, 20)
 datetime.date(2015, 1, 21) datetime.date(2015, 1, 22)
 datetime.date(2015, 1, 23) datetime.date(2015, 1, 24)
 datetime.date(2015, 1, 25) datetime.date(2015, 1, 26)
 datetime.date(2015, 1, 27) datetime.date(2015, 1, 28)
 datetime.date(2015, 1, 29) datetime.date(2015, 1, 30)
 datetime.date(2015, 1, 31) datetime.date(2015, 2, 1)
 datetime.date(2015, 2, 3) datetime.date(2015, 2, 4)
 datetime.date(2015, 2, 5) datetime.date(2015, 2, 6)
 datetime.date(2015, 2, 7) datetime.date(2015, 2, 8)
 datetime.date(2015, 2, 9) datetime.date(2015, 2, 10)
 datetime.date(2015, 2, 11) datetime.date(2015, 2, 12)
 datetime.date(2015, 2, 13) datetime.date(2015, 2, 20)
 datetime.date(2015, 2, 21) datetime.date(2015, 2, 22)
 datetime.date(2015, 2, 23) datetime.date(2015, 2, 24)
 datetime.date(2015, 2, 25) datetime.date(2015, 2, 26)
 datetime.date(2015, 2, 27) datetime.date(2015, 2, 28)
 datetime.date(2015, 3, 1) datetime.date(2015, 3, 2)
 datetime.date(2015, 3, 3) datetime.date(2015, 3, 4)
 datetime.date(2015, 3, 5) datetime.date(2015, 3, 6)
 datetime.date(2015, 3, 7) datetime.date(2015, 3, 8)
 datetime.date(2015, 3, 9) datetime.date(2015, 3, 10)
 datetime.date(2015, 3, 11) datetime.date(2015, 3, 12)
 datetime.date(2015, 3, 13) datetime.date(2015, 3, 14)
 datetime.date(2015, 3, 15) datetime.date(2015, 3, 16)
 datetime.date(2015, 3, 17) datetime.date(2015, 3, 18)
 datetime.date(2015, 3, 19) datetime.date(2015, 3, 20)
 datetime.date(2015, 3, 21) datetime.date(2015, 3, 22)
 datetime.date(2015, 3, 23) datetime.date(2015, 3, 24)
 datetime.date(2015, 3, 25) datetime.date(2015, 3, 26)
 datetime.date(2015, 3, 27) datetime.date(2015, 3, 28)
 datetime.date(2015, 3, 29) datetime.date(2015, 3, 30)
 datetime.date(2015, 3, 31) datetime.date(2015, 4, 1)
 datetime.date(2015, 4, 2) datetime.date(2015, 4, 3)
 datetime.date(2015, 4, 4) datetime.date(2015, 4, 5)
 datetime.date(2015, 4, 6) datetime.date(2015, 4, 7)
 datetime.date(2015, 4, 8) datetime.date(2015, 4, 9)
 datetime.date(2015, 4, 10) datetime.date(2015, 4, 11)
 datetime.date(2015, 4, 12) datetime.date(2015, 4, 13)
 datetime.date(2015, 4, 14) datetime.date(2015, 4, 15)
 datetime.date(2015, 4, 16) datetime.date(2015, 4, 18)
 datetime.date(2015, 4, 19) datetime.date(2015, 4, 20)
 datetime.date(2015, 4, 21) datetime.date(2015, 4, 22)
 datetime.date(2015, 4, 23) datetime.date(2015, 4, 24)
 datetime.date(2015, 4, 25) datetime.date(2015, 4, 26)
 datetime.date(2015, 4, 27) datetime.date(2015, 4, 28)
 datetime.date(2015, 4, 29) datetime.date(2015, 4, 30)
 datetime.date(2015, 5, 1) datetime.date(2015, 5, 2)
 datetime.date(2015, 5, 3) datetime.date(2015, 5, 4)
 datetime.date(2015, 5, 5) datetime.date(2015, 5, 6)
 datetime.date(2015, 5, 7) datetime.date(2015, 5, 9)
 datetime.date(2015, 5, 10) datetime.date(2015, 5, 11)
 datetime.date(2015, 5, 12) datetime.date(2015, 5, 13)
 datetime.date(2015, 5, 14) datetime.date(2015, 5, 15)
 datetime.date(2015, 5, 16) datetime.date(2015, 5, 17)
 datetime.date(2015, 5, 20) datetime.date(2015, 5, 21)
 datetime.date(2015, 5, 22) datetime.date(2015, 5, 23)
 datetime.date(2015, 5, 24) datetime.date(2015, 5, 25)
 datetime.date(2015, 5, 26) datetime.date(2015, 5, 27)
 datetime.date(2015, 5, 28) datetime.date(2015, 6, 5)
 datetime.date(2015, 6, 8) datetime.date(2015, 6, 10)
 datetime.date(2015, 6, 12) datetime.date(2015, 6, 15)
 datetime.date(2015, 6, 17)]

In [28]:
df_fourteen.to_csv('2014_schedule.csv')

In [29]:
pd.read_csv('2014_schedule.csv', index_col=0)

,home_team_name,home_team_score,start_time,visiting_team_name,visiting_team_score
0,Los Angeles Lakers,90,2014-10-29 02:30:00,Houston Rockets,108
1,New Orleans Pelicans,101,2014-10-29 00:00:00,Orlando Magic,84
2,San Antonio Spurs,101,2014-10-29 00:00:00,Dallas Mavericks,100
3,Boston Celtics,121,2014-10-29 23:30:00,Brooklyn Nets,105
4,Charlotte Hornets,108,2014-10-29 23:00:00,Milwaukee Bucks,106
5,Denver Nuggets,89,2014-10-30 01:00:00,Detroit Pistons,79
6,Indiana Pacers,103,2014-10-29 23:00:00,Philadelphia 76ers,91
7,Memphis Grizzlies,105,2014-10-30 00:00:00,Minnesota Timberwolves,101
8,Miami Heat,107,2014-10-29 23:30:00,Washington Wizards,95
9,New York Knicks,80,2014-10-30 00:00:00,Chicago Bulls,104
10,Phoenix Suns,119,2014-10-30 02:00:00,Los Angeles Lakers,99
11,Portland Trail Blazers,106,2014-10-30 02:30:00,Oklahoma City Thunder,89
12,Sacramento Kings,77,2014-10-30 02:00:00,Golden State Warriors,95
13,Toronto Raptors,109,2014-10-29 23:30:00,Atlanta Hawks,102
14,Utah Jazz,93,2014-10-30 01:00:00,Houston Rockets,104
15,Cleveland Cavaliers,90,2014-10-31 00:00:00,New York Knicks,95
16,Dallas Mavericks,120,2014-10-31 00:30:00,Utah Jazz,102
17,Los Angeles Clippers,93,2014-10-31 02:30:00,Oklahoma City Thunder,90
18,Minnesota Timberwolves,97,2014-10-31 00:00:00,Detroit Pistons,91
19,Orlando Magic,98,2014-10-30 23:00:00,Washington Wizards,105
20,Chicago Bulls,108,2014-11-01 00:00:00,Cleveland Cavaliers,114
21,Indiana Pacers,89,2014-10-31 23:00:00,Memphis Grizzlies,97
22,Los Angeles Lakers,111,2014-11-01 02:30:00,Los Angeles Clippers,118
23,Milwaukee Bucks,93,2014-11-01 00:30:00,Philadelphia 76ers,81
24,Phoenix Suns,94,2014-11-01 02:00:00,San Antonio Spurs,89
25,Sacramento Kings,103,2014-11-01 02:00:00,Portland Trail Blazers,94
26,Atlanta Hawks,102,2014-11-01 23:30:00,Indiana Pacers,92
27,Charlotte Hornets,69,2014-11-01 23:00:00,Memphis Grizzlies,71
28,Detroit Pistons,90,2014-11-01 23:30:00,Brooklyn Nets,102
29,Golden State Warriors,127,2014-11-02 02:30:00,Los Angeles Lakers,104
...,...,...,...,...,...
1281,Memphis Grizzlies,99,2015-05-10 00:00:00,Golden State Warriors,89
1282,Washington Wizards,103,2015-05-09 21:00:00,Atlanta Hawks,101
1283,Chicago Bulls,84,2015-05-10 19:30:00,Cleveland Cavaliers,86
1284,Los Angeles Clippers,128,2015-05-11 00:30:00,Houston Rockets,95
1285,Memphis Grizzlies,84,2015-05-12 01:30:00,Golden State Warriors,101
1286,Washington Wizards,101,2015-05-11 23:00:00,Atlanta Hawks,106
1287,Cleveland Cavaliers,106,2015-05-12 23:00:00,Chicago Bulls,101
1288,Houston Rockets,124,2015-05-13 01:30:00,Los Angeles Clippers,103
1289,Atlanta Hawks,82,2015-05-14 00:00:00,Washington Wizards,81
1290,Golden State Warriors,98,2015-05-14 02:30:00,Memphis Grizzlies,78
1291,Chicago Bulls,73,2015-05-15 00:00:00,Cleveland Cavaliers,94
1292,Los Angeles Clippers,107,2015-05-15 02:30:00,Houston Rockets,119
1293,Memphis Grizzlies,95,2015-05-16 01:30:00,Golden State Warriors,108
1294,Washington Wizards,91,2015-05-15 23:00:00,Atlanta Hawks,94
1295,Houston Rockets,113,2015-05-17 19:30:00,Los Angeles Clippers,100
1296,Golden State Warriors,110,2015-05-20 01:00:00,Houston Rockets,106
1297,Atlanta Hawks,89,2015-05-21 00:30:00,Cleveland Cavaliers,97
1298,Golden State Warriors,99,2015-05-22 01:00:00,Houston Rockets,98
1299,Atlanta Hawks,82,2015-05-23 00:30:00,Cleveland Cavaliers,94
1300,Houston Rockets,80,2015-05-24 01:00:00,Golden State Warriors,115
1301,Cleveland Cavaliers,114,2015-05-25 00:30:00,Atlanta Hawks,111
1302,Houston Rockets,128,2015-05-26 01:00:00,Golden State Warriors,115
1303,Cleveland Cavaliers,118,2015-05-27 00:30:00,Atlanta Hawks,88
1304,Golden State Warriors,104,2015-05-28 01:00:00,Houston Rockets,90
1305,Golden State Warriors,108,2015-06-05 01:00:00,Cleveland Cavaliers,100
1306,Golden State Warriors,93,2015-06-08 00:00:00,Cleveland Cavaliers,95
1307,Cleveland Cavaliers,96,2015-06-10 01:00:00,Golden State Warriors,91
1308,Cleveland Cavaliers,82,2015-06-12 01:00:00,Golden State Warriors,103
1309,Golden State Warriors,104,2015-06-15 00:00:00,Cleveland Cavaliers,91
1310,Cleveland Cavaliers,97,2015-06-17 01:00:00,Golden State Warriors,105

In [30]:
fifteen = br.return_json_encoded_schedule(2015)

INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2016_games-october.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2016_games-november.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2016_games-december.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2016_games-january.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2016_games-february.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2016_games-march.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2016_games-april.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2016_games-may.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2016_games-june.html

In [34]:
final_fifteen = ast.literal_eval(fifteen)['parsed_event_list']
with open('fifteen.json', 'a') as _i:
    _i.write(json.dumps(final_fifteen) + '\n')

In [35]:
loaded_fifteen = []
with open('fifteen.json', 'r') as _i:
    loaded_schedule = json.load(_i)
    for game in loaded_schedule:
        loaded_fifteen.append(ast.literal_eval(game))

In [37]:
df_fifteen = pd.DataFrame(loaded_fifteen)
df_fifteen['start_time'] = pd.to_datetime(df_fifteen['start_time'])
df_fifteen.head()

,home_team_name,home_team_score,start_time,visiting_team_name,visiting_team_score
0,Atlanta Hawks,94,2015-10-28 00:00:00,Detroit Pistons,106
1,Chicago Bulls,97,2015-10-28 00:00:00,Cleveland Cavaliers,95
2,Golden State Warriors,111,2015-10-28 02:30:00,New Orleans Pelicans,95
3,Boston Celtics,112,2015-10-28 23:30:00,Philadelphia 76ers,95
4,Brooklyn Nets,100,2015-10-28 23:30:00,Chicago Bulls,115

In [61]:
fifteen_unique_dates = df_fifteen['start_time'].map(lambda t: t.date()).unique()
print(fifteen_unique_dates)

[datetime.date(2015, 10, 28) datetime.date(2015, 10, 29)
 datetime.date(2015, 10, 30) datetime.date(2015, 10, 31)
 datetime.date(2015, 11, 1) datetime.date(2015, 11, 2)
 datetime.date(2015, 11, 3) datetime.date(2015, 11, 4)
 datetime.date(2015, 11, 5) datetime.date(2015, 11, 6)
 datetime.date(2015, 11, 7) datetime.date(2015, 11, 8)
 datetime.date(2015, 11, 9) datetime.date(2015, 11, 10)
 datetime.date(2015, 11, 11) datetime.date(2015, 11, 12)
 datetime.date(2015, 11, 13) datetime.date(2015, 11, 14)
 datetime.date(2015, 11, 15) datetime.date(2015, 11, 16)
 datetime.date(2015, 11, 17) datetime.date(2015, 11, 18)
 datetime.date(2015, 11, 19) datetime.date(2015, 11, 20)
 datetime.date(2015, 11, 21) datetime.date(2015, 11, 22)
 datetime.date(2015, 11, 23) datetime.date(2015, 11, 24)
 datetime.date(2015, 11, 25) datetime.date(2015, 11, 26)
 datetime.date(2015, 11, 28) datetime.date(2015, 11, 29)
 datetime.date(2015, 11, 30) datetime.date(2015, 12, 1)
 datetime.date(2015, 12, 2) datetime.date(2015, 12, 3)
 datetime.date(2015, 12, 4) datetime.date(2015, 12, 5)
 datetime.date(2015, 12, 6) datetime.date(2015, 12, 7)
 datetime.date(2015, 12, 8) datetime.date(2015, 12, 9)
 datetime.date(2015, 12, 10) datetime.date(2015, 12, 11)
 datetime.date(2015, 12, 12) datetime.date(2015, 12, 13)
 datetime.date(2015, 12, 14) datetime.date(2015, 12, 15)
 datetime.date(2015, 12, 16) datetime.date(2015, 12, 17)
 datetime.date(2015, 12, 18) datetime.date(2015, 12, 19)
 datetime.date(2015, 12, 20) datetime.date(2015, 12, 21)
 datetime.date(2015, 12, 22) datetime.date(2015, 12, 23)
 datetime.date(2015, 12, 24) datetime.date(2015, 12, 25)
 datetime.date(2015, 12, 26) datetime.date(2015, 12, 27)
 datetime.date(2015, 12, 28) datetime.date(2015, 12, 29)
 datetime.date(2015, 12, 30) datetime.date(2015, 12, 31)
 datetime.date(2016, 1, 1) datetime.date(2016, 1, 2)
 datetime.date(2016, 1, 3) datetime.date(2016, 1, 4)
 datetime.date(2016, 1, 5) datetime.date(2016, 1, 6)
 datetime.date(2016, 1, 7) datetime.date(2016, 1, 8)
 datetime.date(2016, 1, 9) datetime.date(2016, 1, 10)
 datetime.date(2016, 1, 11) datetime.date(2016, 1, 12)
 datetime.date(2016, 1, 13) datetime.date(2016, 1, 14)
 datetime.date(2016, 1, 15) datetime.date(2016, 1, 16)
 datetime.date(2016, 1, 17) datetime.date(2016, 1, 18)
 datetime.date(2016, 1, 19) datetime.date(2016, 1, 20)
 datetime.date(2016, 1, 21) datetime.date(2016, 1, 22)
 datetime.date(2016, 1, 23) datetime.date(2016, 1, 24)
 datetime.date(2016, 1, 25) datetime.date(2016, 1, 26)
 datetime.date(2016, 1, 27) datetime.date(2016, 1, 28)
 datetime.date(2016, 1, 29) datetime.date(2016, 1, 30)
 datetime.date(2016, 1, 31) datetime.date(2016, 2, 1)
 datetime.date(2016, 2, 2) datetime.date(2016, 2, 3)
 datetime.date(2016, 2, 4) datetime.date(2016, 2, 5)
 datetime.date(2016, 2, 6) datetime.date(2016, 2, 7)
 datetime.date(2016, 2, 9) datetime.date(2016, 2, 10)
 datetime.date(2016, 2, 11) datetime.date(2016, 2, 12)
 datetime.date(2016, 2, 19) datetime.date(2016, 2, 20)
 datetime.date(2016, 2, 21) datetime.date(2016, 2, 22)
 datetime.date(2016, 2, 23) datetime.date(2016, 2, 24)
 datetime.date(2016, 2, 25) datetime.date(2016, 2, 26)
 datetime.date(2016, 2, 27) datetime.date(2016, 2, 28)
 datetime.date(2016, 2, 29) datetime.date(2016, 3, 1)
 datetime.date(2016, 3, 2) datetime.date(2016, 3, 3)
 datetime.date(2016, 3, 4) datetime.date(2016, 3, 5)
 datetime.date(2016, 3, 6) datetime.date(2016, 3, 8)
 datetime.date(2016, 3, 9) datetime.date(2016, 3, 10)
 datetime.date(2016, 3, 11) datetime.date(2016, 3, 12)
 datetime.date(2016, 3, 13) datetime.date(2016, 3, 14)
 datetime.date(2016, 3, 15) datetime.date(2016, 3, 16)
 datetime.date(2016, 3, 17) datetime.date(2016, 3, 18)
 datetime.date(2016, 3, 19) datetime.date(2016, 3, 20)
 datetime.date(2016, 3, 22) datetime.date(2016, 3, 21)
 datetime.date(2016, 3, 23) datetime.date(2016, 3, 24)
 datetime.date(2016, 3, 25) datetime.date(2016, 3, 26)
 datetime.date(2016, 3, 27) datetime.date(2016, 3, 28)
 datetime.date(2016, 3, 29) datetime.date(2016, 3, 30)
 datetime.date(2016, 3, 31) datetime.date(2016, 4, 1)
 datetime.date(2016, 4, 2) datetime.date(2016, 4, 3)
 datetime.date(2016, 4, 4) datetime.date(2016, 4, 6)
 datetime.date(2016, 4, 5) datetime.date(2016, 4, 7)
 datetime.date(2016, 4, 8) datetime.date(2016, 4, 9)
 datetime.date(2016, 4, 10) datetime.date(2016, 4, 11)
 datetime.date(2016, 4, 12) datetime.date(2016, 4, 13)
 datetime.date(2016, 4, 14) datetime.date(2016, 4, 16)
 datetime.date(2016, 4, 17) datetime.date(2016, 4, 18)
 datetime.date(2016, 4, 19) datetime.date(2016, 4, 20)
 datetime.date(2016, 4, 21) datetime.date(2016, 4, 22)
 datetime.date(2016, 4, 23) datetime.date(2016, 4, 24)
 datetime.date(2016, 4, 25) datetime.date(2016, 4, 26)
 datetime.date(2016, 4, 27) datetime.date(2016, 4, 28)
 datetime.date(2016, 4, 29) datetime.date(2016, 4, 30)
 datetime.date(2016, 5, 1) datetime.date(2016, 5, 2)
 datetime.date(2016, 5, 3) datetime.date(2016, 5, 4)
 datetime.date(2016, 5, 5) datetime.date(2016, 5, 6)
 datetime.date(2016, 5, 7) datetime.date(2016, 5, 8)
 datetime.date(2016, 5, 9) datetime.date(2016, 5, 10)
 datetime.date(2016, 5, 11) datetime.date(2016, 5, 12)
 datetime.date(2016, 5, 13) datetime.date(2016, 5, 14)
 datetime.date(2016, 5, 15) datetime.date(2016, 5, 17)
 datetime.date(2016, 5, 18) datetime.date(2016, 5, 19)
 datetime.date(2016, 5, 20) datetime.date(2016, 5, 22)
 datetime.date(2016, 5, 23) datetime.date(2016, 5, 24)
 datetime.date(2016, 5, 25) datetime.date(2016, 5, 26)
 datetime.date(2016, 5, 27) datetime.date(2016, 5, 28)
 datetime.date(2016, 5, 29) datetime.date(2016, 5, 31)
 datetime.date(2016, 6, 3) datetime.date(2016, 6, 6)
 datetime.date(2016, 6, 9) datetime.date(2016, 6, 11)
 datetime.date(2016, 6, 14) datetime.date(2016, 6, 17)
 datetime.date(2016, 6, 20)]

In [62]:
df_fifteen.to_csv('2015_schedule.csv')

In [63]:
pd.read_csv('2015_schedule.csv',index_col=0)

,home_team_name,home_team_score,start_time,visiting_team_name,visiting_team_score
0,Atlanta Hawks,94,2015-10-28 00:00:00,Detroit Pistons,106
1,Chicago Bulls,97,2015-10-28 00:00:00,Cleveland Cavaliers,95
2,Golden State Warriors,111,2015-10-28 02:30:00,New Orleans Pelicans,95
3,Boston Celtics,112,2015-10-28 23:30:00,Philadelphia 76ers,95
4,Brooklyn Nets,100,2015-10-28 23:30:00,Chicago Bulls,115
5,Detroit Pistons,92,2015-10-28 23:30:00,Utah Jazz,87
6,Houston Rockets,85,2015-10-29 00:00:00,Denver Nuggets,105
7,Los Angeles Lakers,111,2015-10-29 02:30:00,Minnesota Timberwolves,112
8,Memphis Grizzlies,76,2015-10-29 00:00:00,Cleveland Cavaliers,106
9,Miami Heat,104,2015-10-28 23:30:00,Charlotte Hornets,94
10,Milwaukee Bucks,97,2015-10-29 00:00:00,New York Knicks,122
11,Oklahoma City Thunder,112,2015-10-29 00:00:00,San Antonio Spurs,106
12,Orlando Magic,87,2015-10-28 23:00:00,Washington Wizards,88
13,Phoenix Suns,95,2015-10-29 02:00:00,Dallas Mavericks,111
14,Portland Trail Blazers,112,2015-10-29 02:00:00,New Orleans Pelicans,94
15,Sacramento Kings,104,2015-10-29 02:00:00,Los Angeles Clippers,111
16,Toronto Raptors,106,2015-10-28 23:30:00,Indiana Pacers,99
17,Indiana Pacers,103,2015-10-29 23:00:00,Memphis Grizzlies,112
18,Los Angeles Clippers,104,2015-10-30 02:30:00,Dallas Mavericks,88
19,New York Knicks,101,2015-10-30 00:00:00,Atlanta Hawks,112
20,Atlanta Hawks,97,2015-10-31 00:00:00,Charlotte Hornets,94
21,Boston Celtics,103,2015-10-30 23:30:00,Toronto Raptors,113
22,Cleveland Cavaliers,102,2015-10-30 23:00:00,Miami Heat,92
23,Denver Nuggets,78,2015-10-31 01:00:00,Minnesota Timberwolves,95
24,Detroit Pistons,98,2015-10-30 23:30:00,Chicago Bulls,94
25,Houston Rockets,92,2015-10-31 01:30:00,Golden State Warriors,112
26,Milwaukee Bucks,113,2015-10-31 00:00:00,Washington Wizards,118
27,Orlando Magic,136,2015-10-30 23:00:00,Oklahoma City Thunder,139
28,Philadelphia 76ers,71,2015-10-30 23:00:00,Utah Jazz,99
29,Phoenix Suns,110,2015-10-31 02:30:00,Portland Trail Blazers,92
...,...,...,...,...,...
1286,Atlanta Hawks,99,2016-05-08 19:30:00,Cleveland Cavaliers,100
1287,Oklahoma City Thunder,111,2016-05-09 00:00:00,San Antonio Spurs,97
1288,Miami Heat,94,2016-05-10 00:00:00,Toronto Raptors,87
1289,Portland Trail Blazers,125,2016-05-10 02:30:00,Golden State Warriors,132
1290,San Antonio Spurs,91,2016-05-11 00:00:00,Oklahoma City Thunder,95
1291,Golden State Warriors,125,2016-05-12 02:30:00,Portland Trail Blazers,121
1292,Toronto Raptors,99,2016-05-12 00:00:00,Miami Heat,91
1293,Oklahoma City Thunder,113,2016-05-13 00:30:00,San Antonio Spurs,99
1294,Miami Heat,103,2016-05-14 00:00:00,Toronto Raptors,91
1295,Toronto Raptors,116,2016-05-15 19:30:00,Miami Heat,89
1296,Golden State Warriors,102,2016-05-17 01:00:00,Oklahoma City Thunder,108
1297,Cleveland Cavaliers,115,2016-05-18 00:30:00,Toronto Raptors,84
1298,Golden State Warriors,118,2016-05-19 01:00:00,Oklahoma City Thunder,91
1299,Cleveland Cavaliers,108,2016-05-20 00:30:00,Toronto Raptors,89
1300,Toronto Raptors,99,2016-05-22 00:30:00,Cleveland Cavaliers,84
1301,Oklahoma City Thunder,133,2016-05-23 00:00:00,Golden State Warriors,105
1302,Toronto Raptors,105,2016-05-24 00:30:00,Cleveland Cavaliers,99
1303,Oklahoma City Thunder,118,2016-05-25 01:00:00,Golden State Warriors,94
1304,Cleveland Cavaliers,116,2016-05-26 00:30:00,Toronto Raptors,78
1305,Golden State Warriors,120,2016-05-27 01:00:00,Oklahoma City Thunder,111
1306,Toronto Raptors,87,2016-05-28 00:30:00,Cleveland Cavaliers,113
1307,Oklahoma City Thunder,101,2016-05-29 01:00:00,Golden State Warriors,108
1308,Golden State Warriors,96,2016-05-31 01:00:00,Oklahoma City Thunder,88
1309,Golden State Warriors,104,2016-06-03 01:00:00,Cleveland Cavaliers,89
1310,Golden State Warriors,110,2016-06-06 00:00:00,Cleveland Cavaliers,77
1311,Cleveland Cavaliers,120,2016-06-09 01:00:00,Golden State Warriors,90
1312,Cleveland Cavaliers,97,2016-06-11 01:00:00,Golden State Warriors,108
1313,Golden State Warriors,97,2016-06-14 01:00:00,Cleveland Cavaliers,112
1314,Cleveland Cavaliers,115,2016-06-17 01:00:00,Golden State Warriors,101
1315,Golden State Warriors,89,2016-06-20 00:00:00,Cleveland Cavaliers,93

In [38]:
sixteen = br.return_json_encoded_schedule(2016)

INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2017_games-october.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2017_games-november.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2017_games-december.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2017_games-january.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2017_games-february.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2017_games-march.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2017_games-april.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2017_games-may.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2017_games-june.html

In [39]:
final_sixteen = ast.literal_eval(sixteen)['parsed_event_list']
with open('sixteen.json','a') as _j:
    _j.write(json.dumps(final_sixteen) + '\n')

In [40]:
loaded_sixteen = []
with open('sixteen.json','r') as _j:
    loaded_schedule = json.load(_j)
    for game in loaded_schedule:
        loaded_sixteen.append(ast.literal_eval(game))

In [41]:
df_sixteen = pd.DataFrame(loaded_sixteen)
df_sixteen['start_time'] = pd.to_datetime(df_sixteen['start_time'])
df_sixteen.head()

,home_team_name,home_team_score,start_time,visiting_team_name,visiting_team_score
0,Cleveland Cavaliers,117,2016-10-25 23:30:00,New York Knicks,88
1,Golden State Warriors,100,2016-10-26 02:30:00,San Antonio Spurs,129
2,Portland Trail Blazers,113,2016-10-26 02:00:00,Utah Jazz,104
3,Boston Celtics,122,2016-10-26 23:30:00,Brooklyn Nets,117
4,Indiana Pacers,130,2016-10-26 23:00:00,Dallas Mavericks,121

In [43]:
sixteen_unique_dates = df_sixteen['start_time'].map(lambda t: t.date()).unique()
print(sixteen_unique_dates)

[datetime.date(2016, 10, 25) datetime.date(2016, 10, 26)
 datetime.date(2016, 10, 27) datetime.date(2016, 10, 28)
 datetime.date(2016, 10, 29) datetime.date(2016, 10, 30)
 datetime.date(2016, 10, 31) datetime.date(2016, 11, 1)
 datetime.date(2016, 11, 2) datetime.date(2016, 11, 3)
 datetime.date(2016, 11, 4) datetime.date(2016, 11, 5)
 datetime.date(2016, 11, 6) datetime.date(2016, 11, 7)
 datetime.date(2016, 11, 8) datetime.date(2016, 11, 9)
 datetime.date(2016, 11, 10) datetime.date(2016, 11, 11)
 datetime.date(2016, 11, 12) datetime.date(2016, 11, 13)
 datetime.date(2016, 11, 14) datetime.date(2016, 11, 15)
 datetime.date(2016, 11, 16) datetime.date(2016, 11, 17)
 datetime.date(2016, 11, 18) datetime.date(2016, 11, 19)
 datetime.date(2016, 11, 20) datetime.date(2016, 11, 21)
 datetime.date(2016, 11, 22) datetime.date(2016, 11, 23)
 datetime.date(2016, 11, 24) datetime.date(2016, 11, 25)
 datetime.date(2016, 11, 26) datetime.date(2016, 11, 27)
 datetime.date(2016, 11, 28) datetime.date(2016, 11, 29)
 datetime.date(2016, 11, 30) datetime.date(2016, 12, 1)
 datetime.date(2016, 12, 2) datetime.date(2016, 12, 3)
 datetime.date(2016, 12, 4) datetime.date(2016, 12, 5)
 datetime.date(2016, 12, 6) datetime.date(2016, 12, 7)
 datetime.date(2016, 12, 8) datetime.date(2016, 12, 9)
 datetime.date(2016, 12, 10) datetime.date(2016, 12, 11)
 datetime.date(2016, 12, 12) datetime.date(2016, 12, 13)
 datetime.date(2016, 12, 14) datetime.date(2016, 12, 15)
 datetime.date(2016, 12, 16) datetime.date(2016, 12, 17)
 datetime.date(2016, 12, 18) datetime.date(2016, 12, 19)
 datetime.date(2016, 12, 20) datetime.date(2016, 12, 21)
 datetime.date(2016, 12, 22) datetime.date(2016, 12, 23)
 datetime.date(2016, 12, 24) datetime.date(2016, 12, 25)
 datetime.date(2016, 12, 26) datetime.date(2016, 12, 27)
 datetime.date(2016, 12, 28) datetime.date(2016, 12, 29)
 datetime.date(2016, 12, 30) datetime.date(2016, 12, 31)
 datetime.date(2017, 1, 1) datetime.date(2017, 1, 2)
 datetime.date(2017, 1, 3) datetime.date(2017, 1, 4)
 datetime.date(2017, 1, 5) datetime.date(2017, 1, 6)
 datetime.date(2017, 1, 7) datetime.date(2017, 1, 8)
 datetime.date(2017, 1, 9) datetime.date(2017, 1, 10)
 datetime.date(2017, 1, 11) datetime.date(2017, 1, 12)
 datetime.date(2017, 1, 13) datetime.date(2017, 1, 14)
 datetime.date(2017, 1, 15) datetime.date(2017, 1, 16)
 datetime.date(2017, 1, 17) datetime.date(2017, 1, 18)
 datetime.date(2017, 1, 19) datetime.date(2017, 1, 20)
 datetime.date(2017, 1, 21) datetime.date(2017, 1, 22)
 datetime.date(2017, 1, 23) datetime.date(2017, 1, 24)
 datetime.date(2017, 1, 25) datetime.date(2017, 1, 26)
 datetime.date(2017, 1, 27) datetime.date(2017, 1, 28)
 datetime.date(2017, 1, 29) datetime.date(2017, 1, 30)
 datetime.date(2017, 1, 31) datetime.date(2017, 2, 1)
 datetime.date(2017, 2, 2) datetime.date(2017, 2, 3)
 datetime.date(2017, 2, 4) datetime.date(2017, 2, 5)
 datetime.date(2017, 2, 7) datetime.date(2017, 2, 8)
 datetime.date(2017, 2, 9) datetime.date(2017, 2, 10)
 datetime.date(2017, 2, 11) datetime.date(2017, 2, 12)
 datetime.date(2017, 2, 13) datetime.date(2017, 2, 14)
 datetime.date(2017, 2, 15) datetime.date(2017, 2, 16)
 datetime.date(2017, 2, 17) datetime.date(2017, 2, 24)
 datetime.date(2017, 2, 25) datetime.date(2017, 2, 26)
 datetime.date(2017, 2, 27) datetime.date(2017, 2, 28)
 datetime.date(2017, 3, 1) datetime.date(2017, 3, 2)
 datetime.date(2017, 3, 3) datetime.date(2017, 3, 4)
 datetime.date(2017, 3, 5) datetime.date(2017, 3, 6)
 datetime.date(2017, 3, 7) datetime.date(2017, 3, 8)
 datetime.date(2017, 3, 9) datetime.date(2017, 3, 10)
 datetime.date(2017, 3, 11) datetime.date(2017, 3, 12)
 datetime.date(2017, 3, 13) datetime.date(2017, 3, 14)
 datetime.date(2017, 3, 15) datetime.date(2017, 3, 16)
 datetime.date(2017, 3, 17) datetime.date(2017, 3, 18)
 datetime.date(2017, 3, 19) datetime.date(2017, 3, 20)
 datetime.date(2017, 3, 21) datetime.date(2017, 3, 22)
 datetime.date(2017, 3, 23) datetime.date(2017, 3, 24)
 datetime.date(2017, 3, 25) datetime.date(2017, 3, 26)
 datetime.date(2017, 3, 27) datetime.date(2017, 3, 28)
 datetime.date(2017, 3, 29) datetime.date(2017, 3, 30)
 datetime.date(2017, 3, 31) datetime.date(2017, 4, 1)
 datetime.date(2017, 4, 2) datetime.date(2017, 4, 3)
 datetime.date(2017, 4, 4) datetime.date(2017, 4, 5)
 datetime.date(2017, 4, 6) datetime.date(2017, 4, 7)
 datetime.date(2017, 4, 8) datetime.date(2017, 4, 9)
 datetime.date(2017, 4, 10) datetime.date(2017, 4, 11)
 datetime.date(2017, 4, 12) datetime.date(2017, 4, 13)
 datetime.date(2017, 4, 15) datetime.date(2017, 4, 16)
 datetime.date(2017, 4, 17) datetime.date(2017, 4, 18)
 datetime.date(2017, 4, 19) datetime.date(2017, 4, 20)
 datetime.date(2017, 4, 21) datetime.date(2017, 4, 22)
 datetime.date(2017, 4, 23) datetime.date(2017, 4, 24)
 datetime.date(2017, 4, 25) datetime.date(2017, 4, 26)
 datetime.date(2017, 4, 27) datetime.date(2017, 4, 28)
 datetime.date(2017, 4, 29) datetime.date(2017, 4, 30)
 datetime.date(2017, 5, 1) datetime.date(2017, 5, 2)
 datetime.date(2017, 5, 3) datetime.date(2017, 5, 4)
 datetime.date(2017, 5, 5) datetime.date(2017, 5, 6)
 datetime.date(2017, 5, 7) datetime.date(2017, 5, 8)
 datetime.date(2017, 5, 9) datetime.date(2017, 5, 10)
 datetime.date(2017, 5, 11) datetime.date(2017, 5, 12)
 datetime.date(2017, 5, 13) datetime.date(2017, 5, 14)
 datetime.date(2017, 5, 16) datetime.date(2017, 5, 17)
 datetime.date(2017, 5, 18) datetime.date(2017, 5, 20)
 datetime.date(2017, 5, 21) datetime.date(2017, 5, 22)
 datetime.date(2017, 5, 23) datetime.date(2017, 5, 24)
 datetime.date(2017, 5, 26) datetime.date(2017, 6, 2)
 datetime.date(2017, 6, 5) datetime.date(2017, 6, 8)
 datetime.date(2017, 6, 10) datetime.date(2017, 6, 13)]

In [44]:
df_sixteen.to_csv('2016_schedule.csv')

In [45]:
pd.read_csv('2016_schedule.csv', index_col=0)

,home_team_name,home_team_score,start_time,visiting_team_name,visiting_team_score
0,Cleveland Cavaliers,117,2016-10-25 23:30:00,New York Knicks,88
1,Golden State Warriors,100,2016-10-26 02:30:00,San Antonio Spurs,129
2,Portland Trail Blazers,113,2016-10-26 02:00:00,Utah Jazz,104
3,Boston Celtics,122,2016-10-26 23:30:00,Brooklyn Nets,117
4,Indiana Pacers,130,2016-10-26 23:00:00,Dallas Mavericks,121
5,Los Angeles Lakers,120,2016-10-27 02:30:00,Houston Rockets,114
6,Memphis Grizzlies,102,2016-10-27 00:00:00,Minnesota Timberwolves,98
7,Milwaukee Bucks,96,2016-10-27 00:00:00,Charlotte Hornets,107
8,New Orleans Pelicans,102,2016-10-27 00:00:00,Denver Nuggets,107
9,Orlando Magic,96,2016-10-26 23:00:00,Miami Heat,108
10,Philadelphia 76ers,97,2016-10-27 00:00:00,Oklahoma City Thunder,103
11,Phoenix Suns,94,2016-10-27 02:00:00,Sacramento Kings,113
12,Toronto Raptors,109,2016-10-26 23:30:00,Detroit Pistons,91
13,Atlanta Hawks,114,2016-10-27 23:30:00,Washington Wizards,99
14,Chicago Bulls,105,2016-10-28 00:00:00,Boston Celtics,99
15,Portland Trail Blazers,106,2016-10-28 02:30:00,Los Angeles Clippers,114
16,Sacramento Kings,94,2016-10-28 02:30:00,San Antonio Spurs,102
17,Brooklyn Nets,103,2016-10-28 23:30:00,Indiana Pacers,94
18,Dallas Mavericks,98,2016-10-29 00:30:00,Houston Rockets,106
19,Detroit Pistons,108,2016-10-28 23:30:00,Orlando Magic,82
20,Miami Heat,91,2016-10-29 00:00:00,Charlotte Hornets,97
21,New Orleans Pelicans,114,2016-10-29 01:30:00,Golden State Warriors,122
22,Oklahoma City Thunder,113,2016-10-29 00:00:00,Phoenix Suns,110
23,Toronto Raptors,91,2016-10-28 23:00:00,Cleveland Cavaliers,94
24,Utah Jazz,96,2016-10-29 01:00:00,Los Angeles Lakers,89
25,Chicago Bulls,118,2016-10-30 00:00:00,Indiana Pacers,101
26,Charlotte Hornets,98,2016-10-29 23:00:00,Boston Celtics,104
27,Cleveland Cavaliers,105,2016-10-29 23:30:00,Orlando Magic,99
28,Denver Nuggets,113,2016-10-30 01:00:00,Portland Trail Blazers,115
29,Milwaukee Bucks,110,2016-10-30 00:00:00,Brooklyn Nets,108
...,...,...,...,...,...
1279,Cleveland Cavaliers,125,2017-05-03 23:00:00,Toronto Raptors,103
1280,San Antonio Spurs,121,2017-05-04 01:30:00,Houston Rockets,96
1281,Golden State Warriors,115,2017-05-05 02:30:00,Utah Jazz,104
1282,Washington Wizards,116,2017-05-05 00:00:00,Boston Celtics,89
1283,Houston Rockets,92,2017-05-06 01:30:00,San Antonio Spurs,103
1284,Toronto Raptors,94,2017-05-05 23:00:00,Cleveland Cavaliers,115
1285,Utah Jazz,91,2017-05-07 00:30:00,Golden State Warriors,102
1286,Houston Rockets,125,2017-05-08 01:00:00,San Antonio Spurs,104
1287,Toronto Raptors,102,2017-05-07 19:30:00,Cleveland Cavaliers,109
1288,Washington Wizards,121,2017-05-07 22:30:00,Boston Celtics,102
1289,Utah Jazz,95,2017-05-09 01:00:00,Golden State Warriors,121
1290,San Antonio Spurs,110,2017-05-10 00:00:00,Houston Rockets,107
1291,Boston Celtics,123,2017-05-11 00:00:00,Washington Wizards,101
1292,Houston Rockets,75,2017-05-12 00:00:00,San Antonio Spurs,114
1293,Washington Wizards,92,2017-05-13 00:00:00,Boston Celtics,91
1294,Golden State Warriors,113,2017-05-14 19:30:00,San Antonio Spurs,111
1295,Boston Celtics,115,2017-05-16 00:00:00,Washington Wizards,105
1296,Golden State Warriors,136,2017-05-17 01:00:00,San Antonio Spurs,100
1297,Boston Celtics,104,2017-05-18 00:30:00,Cleveland Cavaliers,117
1298,Boston Celtics,86,2017-05-20 00:30:00,Cleveland Cavaliers,130
1299,San Antonio Spurs,108,2017-05-21 01:00:00,Golden State Warriors,120
1300,Cleveland Cavaliers,108,2017-05-22 00:30:00,Boston Celtics,111
1301,San Antonio Spurs,115,2017-05-23 01:00:00,Golden State Warriors,129
1302,Cleveland Cavaliers,112,2017-05-24 00:30:00,Boston Celtics,99
1303,Boston Celtics,102,2017-05-26 00:30:00,Cleveland Cavaliers,135
1304,Golden State Warriors,113,2017-06-02 01:00:00,Cleveland Cavaliers,91
1305,Golden State Warriors,132,2017-06-05 00:00:00,Cleveland Cavaliers,113
1306,Cleveland Cavaliers,113,2017-06-08 01:00:00,Golden State Warriors,118
1307,Cleveland Cavaliers,137,2017-06-10 01:00:00,Golden State Warriors,116
1308,Golden State Warriors,129,2017-06-13 01:00:00,Cleveland Cavaliers,120

In [46]:
seventeen = br.return_json_encoded_schedule(2017)

INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2018_games-october.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2018_games-november.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2018_games-december.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2018_games-january.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2018_games-february.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2018_games-march.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2018_games-april.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2018_games-may.html
INFO:main:schedule url: http://www.basketball-reference.com/leagues/NBA_2018_games-june.html

In [47]:
final_seventeen = ast.literal_eval(seventeen)['parsed_event_list']
with open('seventeen.json', 'a') as _k:
    _k.write(json.dumps(final_seventeen) + '\n')

In [49]:
loaded_seventeen = []
with open('seventeen.json', 'r') as _k:
    loaded_schedule = json.load(_k)
    for game in loaded_schedule:
        loaded_seventeen.append(ast.literal_eval(game))

In [50]:
df_seventeen = pd.DataFrame(loaded_seventeen)
df_seventeen['start_time'] = pd.to_datetime(df_seventeen['start_time'])
df_seventeen.head()

,home_team_name,home_team_score,start_time,visiting_team_name,visiting_team_score
0,Cleveland Cavaliers,102,2017-10-18 00:01:00,Boston Celtics,99
1,Golden State Warriors,121,2017-10-18 02:30:00,Houston Rockets,122
2,Boston Celtics,100,2017-10-18 23:30:00,Milwaukee Bucks,108
3,Dallas Mavericks,111,2017-10-19 00:30:00,Atlanta Hawks,117
4,Detroit Pistons,102,2017-10-18 23:00:00,Charlotte Hornets,90

In [51]:
seventeen_unique_dates = df_seventeen['start_time'].map(lambda t: t.date()).unique()
print(seventeen_unique_dates)

[datetime.date(2017, 10, 18) datetime.date(2017, 10, 19)
 datetime.date(2017, 10, 20) datetime.date(2017, 10, 21)
 datetime.date(2017, 10, 22) datetime.date(2017, 10, 23)
 datetime.date(2017, 10, 24) datetime.date(2017, 10, 25)
 datetime.date(2017, 10, 26) datetime.date(2017, 10, 27)
 datetime.date(2017, 10, 28) datetime.date(2017, 10, 29)
 datetime.date(2017, 10, 30) datetime.date(2017, 10, 31)
 datetime.date(2017, 11, 1) datetime.date(2017, 11, 2)
 datetime.date(2017, 11, 3) datetime.date(2017, 11, 4)
 datetime.date(2017, 11, 5) datetime.date(2017, 11, 6)
 datetime.date(2017, 11, 7) datetime.date(2017, 11, 8)
 datetime.date(2017, 11, 9) datetime.date(2017, 11, 10)
 datetime.date(2017, 11, 11) datetime.date(2017, 11, 12)
 datetime.date(2017, 11, 13) datetime.date(2017, 11, 14)
 datetime.date(2017, 11, 15) datetime.date(2017, 11, 16)
 datetime.date(2017, 11, 17) datetime.date(2017, 11, 18)
 datetime.date(2017, 11, 19) datetime.date(2017, 11, 20)
 datetime.date(2017, 11, 21) datetime.date(2017, 11, 22)
 datetime.date(2017, 11, 23) datetime.date(2017, 11, 25)
 datetime.date(2017, 11, 24) datetime.date(2017, 11, 26)
 datetime.date(2017, 11, 28) datetime.date(2017, 11, 29)
 datetime.date(2017, 11, 30) datetime.date(2017, 12, 1)
 datetime.date(2017, 12, 2) datetime.date(2017, 12, 3)
 datetime.date(2017, 12, 4) datetime.date(2017, 12, 5)
 datetime.date(2017, 12, 6) datetime.date(2017, 12, 7)
 datetime.date(2017, 12, 8) datetime.date(2017, 12, 9)
 datetime.date(2017, 12, 10) datetime.date(2017, 12, 11)
 datetime.date(2017, 12, 12) datetime.date(2017, 12, 13)
 datetime.date(2017, 12, 14) datetime.date(2017, 12, 15)
 datetime.date(2017, 12, 16) datetime.date(2017, 12, 17)
 datetime.date(2017, 12, 19) datetime.date(2017, 12, 20)
 datetime.date(2017, 12, 21) datetime.date(2017, 12, 22)
 datetime.date(2017, 12, 23) datetime.date(2017, 12, 24)
 datetime.date(2017, 12, 25) datetime.date(2017, 12, 26)
 datetime.date(2017, 12, 27) datetime.date(2017, 12, 28)
 datetime.date(2017, 12, 29) datetime.date(2017, 12, 30)
 datetime.date(2017, 12, 31) datetime.date(2018, 1, 1)
 datetime.date(2018, 1, 2) datetime.date(2018, 1, 3)
 datetime.date(2018, 1, 4) datetime.date(2018, 1, 5)
 datetime.date(2018, 1, 6) datetime.date(2018, 1, 7)
 datetime.date(2018, 1, 8) datetime.date(2018, 1, 9)
 datetime.date(2018, 1, 10) datetime.date(2018, 1, 11)
 datetime.date(2018, 1, 12) datetime.date(2018, 1, 13)
 datetime.date(2018, 1, 14) datetime.date(2018, 1, 15)
 datetime.date(2018, 1, 16) datetime.date(2018, 1, 17)
 datetime.date(2018, 1, 18) datetime.date(2018, 1, 19)
 datetime.date(2018, 1, 20) datetime.date(2018, 1, 21)
 datetime.date(2018, 1, 22) datetime.date(2018, 1, 23)
 datetime.date(2018, 1, 24) datetime.date(2018, 1, 25)
 datetime.date(2018, 1, 26) datetime.date(2018, 1, 27)
 datetime.date(2018, 1, 28) datetime.date(2018, 1, 29)
 datetime.date(2018, 1, 30) datetime.date(2018, 1, 31)
 datetime.date(2018, 2, 1) datetime.date(2018, 2, 2)
 datetime.date(2018, 2, 3) datetime.date(2018, 2, 4)
 datetime.date(2018, 2, 6) datetime.date(2018, 2, 7)
 datetime.date(2018, 2, 8) datetime.date(2018, 2, 9)
 datetime.date(2018, 2, 10) datetime.date(2018, 2, 11)
 datetime.date(2018, 2, 12) datetime.date(2018, 2, 13)
 datetime.date(2018, 2, 14) datetime.date(2018, 2, 15)
 datetime.date(2018, 2, 16) datetime.date(2018, 2, 23)
 datetime.date(2018, 2, 24) datetime.date(2018, 2, 25)
 datetime.date(2018, 2, 26) datetime.date(2018, 2, 27)
 datetime.date(2018, 2, 28) datetime.date(2018, 3, 1)
 datetime.date(2018, 3, 2) datetime.date(2018, 3, 3)
 datetime.date(2018, 3, 4) datetime.date(2018, 3, 5)
 datetime.date(2018, 3, 6) datetime.date(2018, 3, 7)
 datetime.date(2018, 3, 8) datetime.date(2018, 3, 9)
 datetime.date(2018, 3, 10) datetime.date(2018, 3, 11)
 datetime.date(2018, 3, 12) datetime.date(2018, 3, 13)
 datetime.date(2018, 3, 14) datetime.date(2018, 3, 15)
 datetime.date(2018, 3, 16) datetime.date(2018, 3, 17)
 datetime.date(2018, 3, 18) datetime.date(2018, 3, 19)
 datetime.date(2018, 3, 20) datetime.date(2018, 3, 21)
 datetime.date(2018, 3, 22) datetime.date(2018, 3, 23)
 datetime.date(2018, 3, 24) datetime.date(2018, 3, 25)
 datetime.date(2018, 3, 26) datetime.date(2018, 3, 27)
 datetime.date(2018, 3, 28) datetime.date(2018, 3, 29)
 datetime.date(2018, 3, 30) datetime.date(2018, 3, 31)
 datetime.date(2018, 4, 1) datetime.date(2018, 4, 2)
 datetime.date(2018, 4, 4) datetime.date(2018, 4, 3)
 datetime.date(2018, 4, 5) datetime.date(2018, 4, 6)
 datetime.date(2018, 4, 7) datetime.date(2018, 4, 8)
 datetime.date(2018, 4, 9) datetime.date(2018, 4, 10)
 datetime.date(2018, 4, 11) datetime.date(2018, 4, 12)]

In [53]:
df_seventeen.to_csv('2017_schedule.csv')

In [54]:
pd.read_csv('2017_schedule.csv', index_col=0)

,home_team_name,home_team_score,start_time,visiting_team_name,visiting_team_score
0,Cleveland Cavaliers,102.0,2017-10-18 00:01:00,Boston Celtics,99.0
1,Golden State Warriors,121.0,2017-10-18 02:30:00,Houston Rockets,122.0
2,Boston Celtics,100.0,2017-10-18 23:30:00,Milwaukee Bucks,108.0
3,Dallas Mavericks,111.0,2017-10-19 00:30:00,Atlanta Hawks,117.0
4,Detroit Pistons,102.0,2017-10-18 23:00:00,Charlotte Hornets,90.0
5,Indiana Pacers,140.0,2017-10-18 23:00:00,Brooklyn Nets,131.0
6,Memphis Grizzlies,103.0,2017-10-19 00:00:00,New Orleans Pelicans,91.0
7,Orlando Magic,116.0,2017-10-18 23:00:00,Miami Heat,109.0
8,Phoenix Suns,76.0,2017-10-19 02:00:00,Portland Trail Blazers,124.0
9,Sacramento Kings,100.0,2017-10-19 02:00:00,Houston Rockets,105.0
10,San Antonio Spurs,107.0,2017-10-19 01:30:00,Minnesota Timberwolves,99.0
11,Utah Jazz,106.0,2017-10-19 01:00:00,Denver Nuggets,96.0
12,Washington Wizards,120.0,2017-10-18 23:00:00,Philadelphia 76ers,115.0
13,Los Angeles Lakers,92.0,2017-10-20 02:30:00,Los Angeles Clippers,108.0
14,Oklahoma City Thunder,105.0,2017-10-20 00:00:00,New York Knicks,84.0
15,Toronto Raptors,117.0,2017-10-19 23:30:00,Chicago Bulls,100.0
16,Brooklyn Nets,126.0,2017-10-20 23:30:00,Orlando Magic,121.0
17,Charlotte Hornets,109.0,2017-10-20 23:00:00,Atlanta Hawks,91.0
18,Dallas Mavericks,88.0,2017-10-21 00:30:00,Sacramento Kings,93.0
19,Indiana Pacers,96.0,2017-10-20 23:00:00,Portland Trail Blazers,114.0
20,Milwaukee Bucks,97.0,2017-10-20 23:00:00,Cleveland Cavaliers,116.0
21,Minnesota Timberwolves,100.0,2017-10-21 00:00:00,Utah Jazz,97.0
22,New Orleans Pelicans,120.0,2017-10-21 01:30:00,Golden State Warriors,128.0
23,Philadelphia 76ers,92.0,2017-10-20 23:00:00,Boston Celtics,102.0
24,Phoenix Suns,130.0,2017-10-21 02:00:00,Los Angeles Lakers,132.0
25,Washington Wizards,115.0,2017-10-20 23:00:00,Detroit Pistons,111.0
26,Chicago Bulls,77.0,2017-10-22 00:00:00,San Antonio Spurs,87.0
27,Cleveland Cavaliers,93.0,2017-10-22 00:00:00,Orlando Magic,114.0
28,Denver Nuggets,96.0,2017-10-22 01:00:00,Sacramento Kings,79.0
29,Houston Rockets,107.0,2017-10-22 00:00:00,Dallas Mavericks,91.0
...,...,...,...,...,...
1200,Philadelphia 76ers,NaN,2018-04-08 17:00:00,Dallas Mavericks,NaN
1201,Phoenix Suns,NaN,2018-04-09 01:00:00,Golden State Warriors,NaN
1202,Toronto Raptors,NaN,2018-04-08 22:00:00,Orlando Magic,NaN
1203,Brooklyn Nets,NaN,2018-04-09 23:30:00,Chicago Bulls,NaN
1204,Denver Nuggets,NaN,2018-04-10 01:00:00,Portland Trail Blazers,NaN
1205,Detroit Pistons,NaN,2018-04-09 23:00:00,Toronto Raptors,NaN
1206,Los Angeles Clippers,NaN,2018-04-10 02:30:00,New Orleans Pelicans,NaN
1207,Miami Heat,NaN,2018-04-09 23:30:00,Oklahoma City Thunder,NaN
1208,Milwaukee Bucks,NaN,2018-04-10 00:00:00,Orlando Magic,NaN
1209,Minnesota Timberwolves,NaN,2018-04-10 00:00:00,Memphis Grizzlies,NaN
1210,New York Knicks,NaN,2018-04-09 23:30:00,Cleveland Cavaliers,NaN
1211,San Antonio Spurs,NaN,2018-04-10 00:30:00,Sacramento Kings,NaN
1212,Atlanta Hawks,NaN,2018-04-10 23:30:00,Philadelphia 76ers,NaN
1213,Dallas Mavericks,NaN,2018-04-11 00:30:00,Phoenix Suns,NaN
1214,Indiana Pacers,NaN,2018-04-10 23:00:00,Charlotte Hornets,NaN
1215,Los Angeles Lakers,NaN,2018-04-11 02:30:00,Houston Rockets,NaN
1216,Utah Jazz,NaN,2018-04-11 01:00:00,Golden State Warriors,NaN
1217,Washington Wizards,NaN,2018-04-11 00:00:00,Boston Celtics,NaN
1218,Boston Celtics,NaN,2018-04-12 00:00:00,Brooklyn Nets,NaN
1219,Chicago Bulls,NaN,2018-04-12 00:00:00,Detroit Pistons,NaN
1220,Cleveland Cavaliers,NaN,2018-04-12 00:00:00,New York Knicks,NaN
1221,Los Angeles Clippers,NaN,2018-04-12 02:30:00,Los Angeles Lakers,NaN
1222,Miami Heat,NaN,2018-04-12 00:00:00,Toronto Raptors,NaN
1223,Minnesota Timberwolves,NaN,2018-04-12 00:00:00,Denver Nuggets,NaN
1224,New Orleans Pelicans,NaN,2018-04-12 00:00:00,San Antonio Spurs,NaN
1225,Oklahoma City Thunder,NaN,2018-04-12 00:00:00,Memphis Grizzlies,NaN
1226,Orlando Magic,NaN,2018-04-12 00:00:00,Washington Wizards,NaN
1227,Philadelphia 76ers,NaN,2018-04-12 00:00:00,Milwaukee Bucks,NaN
1228,Portland Trail Blazers,NaN,2018-04-12 02:30:00,Utah Jazz,NaN
1229,Sacramento Kings,NaN,2018-04-12 02:30:00,Houston Rockets,NaN

In [56]:
df_final_all = pd.concat([df_twelve, df_thirteen, df_fourteen, df_fifteen, df_sixteen, df_seventeen])
df_final_all

,home_team_name,home_team_score,start_time,visiting_team_name,visiting_team_score
0,Cleveland Cavaliers,94,2012-10-30 23:00:00,Washington Wizards,84
1,Los Angeles Lakers,91,2012-10-30 23:30:00,Dallas Mavericks,99
2,Miami Heat,120,2012-10-31 00:00:00,Boston Celtics,107
3,Chicago Bulls,93,2012-10-31 23:00:00,Sacramento Kings,87
4,Detroit Pistons,96,2012-10-31 23:30:00,Houston Rockets,105
5,Los Angeles Clippers,101,2012-10-31 23:30:00,Memphis Grizzlies,92
6,New Orleans Hornets,95,2012-10-31 23:00:00,San Antonio Spurs,99
7,Philadelphia 76ers,84,2012-10-31 23:00:00,Denver Nuggets,75
8,Phoenix Suns,85,2012-10-31 23:00:00,Golden State Warriors,87
9,Portland Trail Blazers,116,2012-10-31 23:30:00,Los Angeles Lakers,106
10,Toronto Raptors,88,2012-10-31 23:00:00,Indiana Pacers,90
11,Utah Jazz,113,2012-10-31 23:00:00,Dallas Mavericks,94
12,San Antonio Spurs,86,2012-11-02 00:30:00,Oklahoma City Thunder,84
13,Atlanta Hawks,102,2012-11-02 23:30:00,Houston Rockets,109
14,Boston Celtics,88,2012-11-02 23:30:00,Milwaukee Bucks,99
15,Charlotte Bobcats,90,2012-11-02 23:00:00,Indiana Pacers,89
16,Cleveland Cavaliers,86,2012-11-02 23:30:00,Chicago Bulls,115
17,Golden State Warriors,94,2012-11-02 23:30:00,Memphis Grizzlies,104
18,Los Angeles Lakers,95,2012-11-02 23:30:00,Los Angeles Clippers,105
19,Minnesota Timberwolves,92,2012-11-02 23:00:00,Sacramento Kings,80
20,New Orleans Hornets,88,2012-11-02 23:00:00,Utah Jazz,86
21,New York Knicks,104,2012-11-03 00:00:00,Miami Heat,84
22,Oklahoma City Thunder,106,2012-11-02 23:00:00,Portland Trail Blazers,92
23,Orlando Magic,102,2012-11-02 23:00:00,Denver Nuggets,89
24,Phoenix Suns,92,2012-11-02 23:00:00,Detroit Pistons,89
25,Brooklyn Nets,107,2012-11-03 23:30:00,Toronto Raptors,100
26,Chicago Bulls,82,2012-11-03 23:00:00,New Orleans Hornets,89
27,Dallas Mavericks,126,2012-11-03 23:30:00,Charlotte Bobcats,99
28,Houston Rockets,85,2012-11-03 23:00:00,Portland Trail Blazers,95
29,Indiana Pacers,106,2012-11-03 23:00:00,Sacramento Kings,98
...,...,...,...,...,...
1200,Philadelphia 76ers,,2018-04-08 17:00:00,Dallas Mavericks,
1201,Phoenix Suns,,2018-04-09 01:00:00,Golden State Warriors,
1202,Toronto Raptors,,2018-04-08 22:00:00,Orlando Magic,
1203,Brooklyn Nets,,2018-04-09 23:30:00,Chicago Bulls,
1204,Denver Nuggets,,2018-04-10 01:00:00,Portland Trail Blazers,
1205,Detroit Pistons,,2018-04-09 23:00:00,Toronto Raptors,
1206,Los Angeles Clippers,,2018-04-10 02:30:00,New Orleans Pelicans,
1207,Miami Heat,,2018-04-09 23:30:00,Oklahoma City Thunder,
1208,Milwaukee Bucks,,2018-04-10 00:00:00,Orlando Magic,
1209,Minnesota Timberwolves,,2018-04-10 00:00:00,Memphis Grizzlies,
1210,New York Knicks,,2018-04-09 23:30:00,Cleveland Cavaliers,
1211,San Antonio Spurs,,2018-04-10 00:30:00,Sacramento Kings,
1212,Atlanta Hawks,,2018-04-10 23:30:00,Philadelphia 76ers,
1213,Dallas Mavericks,,2018-04-11 00:30:00,Phoenix Suns,
1214,Indiana Pacers,,2018-04-10 23:00:00,Charlotte Hornets,
1215,Los Angeles Lakers,,2018-04-11 02:30:00,Houston Rockets,
1216,Utah Jazz,,2018-04-11 01:00:00,Golden State Warriors,
1217,Washington Wizards,,2018-04-11 00:00:00,Boston Celtics,
1218,Boston Celtics,,2018-04-12 00:00:00,Brooklyn Nets,
1219,Chicago Bulls,,2018-04-12 00:00:00,Detroit Pistons,
1220,Cleveland Cavaliers,,2018-04-12 00:00:00,New York Knicks,
1221,Los Angeles Clippers,,2018-04-12 02:30:00,Los Angeles Lakers,
1222,Miami Heat,,2018-04-12 00:00:00,Toronto Raptors,
1223,Minnesota Timberwolves,,2018-04-12 00:00:00,Denver Nuggets,
1224,New Orleans Pelicans,,2018-04-12 00:00:00,San Antonio Spurs,
1225,Oklahoma City Thunder,,2018-04-12 00:00:00,Memphis Grizzlies,
1226,Orlando Magic,,2018-04-12 00:00:00,Washington Wizards,
1227,Philadelphia 76ers,,2018-04-12 00:00:00,Milwaukee Bucks,
1228,Portland Trail Blazers,,2018-04-12 02:30:00,Utah Jazz,
1229,Sacramento Kings,,2018-04-12 02:30:00,Houston Rockets,

In [59]:
df_final_all.to_csv('2012_2017_schedules.csv')

In [60]:
pd.read_csv('2012_2017_schedules.csv', index_col=0)

,home_team_name,home_team_score,start_time,visiting_team_name,visiting_team_score
0,Cleveland Cavaliers,94.0,2012-10-30 23:00:00,Washington Wizards,84.0
1,Los Angeles Lakers,91.0,2012-10-30 23:30:00,Dallas Mavericks,99.0
2,Miami Heat,120.0,2012-10-31 00:00:00,Boston Celtics,107.0
3,Chicago Bulls,93.0,2012-10-31 23:00:00,Sacramento Kings,87.0
4,Detroit Pistons,96.0,2012-10-31 23:30:00,Houston Rockets,105.0
5,Los Angeles Clippers,101.0,2012-10-31 23:30:00,Memphis Grizzlies,92.0
6,New Orleans Hornets,95.0,2012-10-31 23:00:00,San Antonio Spurs,99.0
7,Philadelphia 76ers,84.0,2012-10-31 23:00:00,Denver Nuggets,75.0
8,Phoenix Suns,85.0,2012-10-31 23:00:00,Golden State Warriors,87.0
9,Portland Trail Blazers,116.0,2012-10-31 23:30:00,Los Angeles Lakers,106.0
10,Toronto Raptors,88.0,2012-10-31 23:00:00,Indiana Pacers,90.0
11,Utah Jazz,113.0,2012-10-31 23:00:00,Dallas Mavericks,94.0
12,San Antonio Spurs,86.0,2012-11-02 00:30:00,Oklahoma City Thunder,84.0
13,Atlanta Hawks,102.0,2012-11-02 23:30:00,Houston Rockets,109.0
14,Boston Celtics,88.0,2012-11-02 23:30:00,Milwaukee Bucks,99.0
15,Charlotte Bobcats,90.0,2012-11-02 23:00:00,Indiana Pacers,89.0
16,Cleveland Cavaliers,86.0,2012-11-02 23:30:00,Chicago Bulls,115.0
17,Golden State Warriors,94.0,2012-11-02 23:30:00,Memphis Grizzlies,104.0
18,Los Angeles Lakers,95.0,2012-11-02 23:30:00,Los Angeles Clippers,105.0
19,Minnesota Timberwolves,92.0,2012-11-02 23:00:00,Sacramento Kings,80.0
20,New Orleans Hornets,88.0,2012-11-02 23:00:00,Utah Jazz,86.0
21,New York Knicks,104.0,2012-11-03 00:00:00,Miami Heat,84.0
22,Oklahoma City Thunder,106.0,2012-11-02 23:00:00,Portland Trail Blazers,92.0
23,Orlando Magic,102.0,2012-11-02 23:00:00,Denver Nuggets,89.0
24,Phoenix Suns,92.0,2012-11-02 23:00:00,Detroit Pistons,89.0
25,Brooklyn Nets,107.0,2012-11-03 23:30:00,Toronto Raptors,100.0
26,Chicago Bulls,82.0,2012-11-03 23:00:00,New Orleans Hornets,89.0
27,Dallas Mavericks,126.0,2012-11-03 23:30:00,Charlotte Bobcats,99.0
28,Houston Rockets,85.0,2012-11-03 23:00:00,Portland Trail Blazers,95.0
29,Indiana Pacers,106.0,2012-11-03 23:00:00,Sacramento Kings,98.0
...,...,...,...,...,...
1200,Philadelphia 76ers,NaN,2018-04-08 17:00:00,Dallas Mavericks,NaN
1201,Phoenix Suns,NaN,2018-04-09 01:00:00,Golden State Warriors,NaN
1202,Toronto Raptors,NaN,2018-04-08 22:00:00,Orlando Magic,NaN
1203,Brooklyn Nets,NaN,2018-04-09 23:30:00,Chicago Bulls,NaN
1204,Denver Nuggets,NaN,2018-04-10 01:00:00,Portland Trail Blazers,NaN
1205,Detroit Pistons,NaN,2018-04-09 23:00:00,Toronto Raptors,NaN
1206,Los Angeles Clippers,NaN,2018-04-10 02:30:00,New Orleans Pelicans,NaN
1207,Miami Heat,NaN,2018-04-09 23:30:00,Oklahoma City Thunder,NaN
1208,Milwaukee Bucks,NaN,2018-04-10 00:00:00,Orlando Magic,NaN
1209,Minnesota Timberwolves,NaN,2018-04-10 00:00:00,Memphis Grizzlies,NaN
1210,New York Knicks,NaN,2018-04-09 23:30:00,Cleveland Cavaliers,NaN
1211,San Antonio Spurs,NaN,2018-04-10 00:30:00,Sacramento Kings,NaN
1212,Atlanta Hawks,NaN,2018-04-10 23:30:00,Philadelphia 76ers,NaN
1213,Dallas Mavericks,NaN,2018-04-11 00:30:00,Phoenix Suns,NaN
1214,Indiana Pacers,NaN,2018-04-10 23:00:00,Charlotte Hornets,NaN
1215,Los Angeles Lakers,NaN,2018-04-11 02:30:00,Houston Rockets,NaN
1216,Utah Jazz,NaN,2018-04-11 01:00:00,Golden State Warriors,NaN
1217,Washington Wizards,NaN,2018-04-11 00:00:00,Boston Celtics,NaN
1218,Boston Celtics,NaN,2018-04-12 00:00:00,Brooklyn Nets,NaN
1219,Chicago Bulls,NaN,2018-04-12 00:00:00,Detroit Pistons,NaN
1220,Cleveland Cavaliers,NaN,2018-04-12 00:00:00,New York Knicks,NaN
1221,Los Angeles Clippers,NaN,2018-04-12 02:30:00,Los Angeles Lakers,NaN
1222,Miami Heat,NaN,2018-04-12 00:00:00,Toronto Raptors,NaN
1223,Minnesota Timberwolves,NaN,2018-04-12 00:00:00,Denver Nuggets,NaN
1224,New Orleans Pelicans,NaN,2018-04-12 00:00:00,San Antonio Spurs,NaN
1225,Oklahoma City Thunder,NaN,2018-04-12 00:00:00,Memphis Grizzlies,NaN
1226,Orlando Magic,NaN,2018-04-12 00:00:00,Washington Wizards,NaN
1227,Philadelphia 76ers,NaN,2018-04-12 00:00:00,Milwaukee Bucks,NaN
1228,Portland Trail Blazers,NaN,2018-04-12 02:30:00,Utah Jazz,NaN
1229,Sacramento Kings,NaN,2018-04-12 02:30:00,Houston Rockets,NaN